// Detailed DSA guides
export const DETAILED_GUIDES = {
  reverse_string: {
    title: "1.1 Đảo ngược chuỗi (Reverse String)",
    meaning: "Đảo ngược chuỗi — biến ký tự đầu thành cuối và ngược lại.",
    definition: "Cho chuỗi s, trả về chuỗi mới (hoặc mutate mảng ký tự) sao cho s[i] nằm ở vị trí n-1-i. Cách kinh điển: hai con trỏ left/right gặp nhau ở giữa.",
    whyLearn: "Đây là bài khởi động hoàn hảo để luyện two-pointer — pattern xuất hiện khắp nơi từ palindrome, two-sum sorted, đến sliding window. Nắm vững reverse string giúp bạn tự tin xử lý mảng/chuỗi in-place mà không tạo bản sao thừa.",
    analogy: "Giống xếp hàng đổi chỗ: người đầu hàng bước xuống cuối, người cuối lên đầu, cứ thế cho đến giữa. Hoặc như gập tờ giấy đôi — nửa trái đổi chỗ với nửa phải.",
    algorithmSteps: "1. Chuyển chuỗi thành mảng ký tự (JS string immutable).\n2. Đặt left = 0, right = length - 1.\n3. Khi left < right: swap chars[left] và chars[right], rồi left++, right--.\n4. Join mảng thành chuỗi và return.",
    howItWorks: "Two-pointer thu hẹp khoảng [left, right]. Mỗi swap đặt đúng 2 ký tự vào vị trí cuối cùng. Sau n/2 lần swap, toàn bộ chuỗi đảo xong. Không cần mảng phụ nếu mutate được (O(1) extra space trên mảng ký tự).",
    dryRun: "Input: \"hello\"\n\nBước 0: h e l l o\n        L       R\n\nBước 1: swap h↔o → o e l l h\n          L   R\n\nBước 2: swap e↔l → o l l e h\n            L/R (left == right → dừng)\n\nOutput: \"olleh\"",
    visualization: "Two-pointer swap:\n\n  h  e  l  l  o\n  ↑           ↑\n  L           R\n\n  o  e  l  l  h\n      ↑   ↑\n      L   R\n\n  o  l  l  e  h\n        ↑\n      done",
    codePattern: "export function reverseString(s) {\n  const chars = s.split(\"\");\n  let left = 0, right = chars.length - 1;\n  while (left < right) {\n    [chars[left], chars[right]] = [chars[right], chars[left]];\n    left++; right--;\n  }\n  return chars.join(\"\");\n}",
    bigO: "Time O(n), Space O(n) với split/join; O(1) extra nếu mutate mảng có sẵn.",
    bigOWhy: "Duyệt nửa mảng → n/2 swap → O(n) thời gian. split() tạo mảng n phần tử → O(n) space. Không dùng split thì chỉ swap tại chỗ trên mảng mutable.",
    commonMistakes: "- Quên JS string immutable — gán s[i] không đổi chuỗi gốc.\n- Dùng left <= right thay vì left < right → swap trùng phần tử giữa 2 lần.\n- Tạo mảng mới bằng unshift trong loop → O(n²) thay vì O(n).",
    compareApproaches: "Two-pointer O(n) in-place trên mảng ký tự là tối ưu. Cách built-in reverse() O(n) dễ đọc nhưng ít thể hiện kỹ năng. Recursive cũng O(n) nhưng tốn stack O(n).",
    interviewTips: "- Nêu rõ immutable string → cần mảng trung gian.\n- Viết loop trước, đề cập recursive nếu interviewer hỏi follow-up.\n- Hỏi có cần in-place hay return chuỗi mới.",
    notes: "LeetCode thường cho char[] — mutate trực tiếp, không cần join.",
  },

  merge_sorted_arrays: {
    title: "1.2 Gộp hai mảng đã sắp xếp (Merge Sorted Arrays)",
    meaning: "Trộn hai mảng đã sort tăng dần thành một mảng sort duy nhất.",
    definition: "Cho nums1 và nums2 đều sorted, tạo mảng kết quả bằng cách mỗi bước chọn phần tử nhỏ hơn từ đầu mỗi mảng — giống merge step trong Merge Sort.",
    whyLearn: "Merge sorted arrays là viên gạch của Merge Sort và nhiều bài two-pointer (intersection, k-way merge). Hiểu bài này giúp bạn giải thích tại sao Merge Sort stable và chạy O(n log n).",
    analogy: "Hai chồng bài đã xếp A→Z trên bàn — mỗi lần bạn lấy lá nhỏ nhất đang nằm trên cùng mỗi chồng, ghép vào chồng thứ ba.",
    algorithmSteps: "1. Khởi tạo i=0, j=0, result=[].\n2. So sánh nums1[i] với nums2[j], push phần tử nhỏ hơn, tăng index tương ứng.\n3. Lặp đến khi một mảng hết.\n4. Append phần còn lại của mảng kia (đã sorted nên copy thẳng).",
    howItWorks: "Hai con trỏ luôn trỏ phần tử nhỏ nhất chưa dùng của mỗi mảng. Tính chất sorted đảm bảo phần tử được chọn là nhỏ nhất toàn cục tại bước đó — không cần sort lại.",
    dryRun: "nums1 = [1, 3, 5]\nnums2 = [2, 4, 6]\n\ni=0,j=0: 1<2 → [1], i=1\ni=1,j=0: 3>2 → [1,2], j=1\ni=1,j=1: 3<4 → [1,2,3], i=2\ni=2,j=1: 5>4 → [1,2,3,4], j=2\ni=2,j=2: 5<6 → [1,2,3,4,5], i=3 (hết)\nappend 6 → [1,2,3,4,5,6]",
    visualization: "  nums1:  1   3   5\n          ↑ i\n  nums2:  2   4   6\n          ↑ j\n\n  result: [1] → [1,2] → [1,2,3] → ...",
    codePattern: "export function mergeSortedArrays(nums1, nums2) {\n  const result = [];\n  let i = 0, j = 0;\n  while (i < nums1.length && j < nums2.length) {\n    if (nums1[i] <= nums2[j]) result.push(nums1[i++]);\n    else result.push(nums2[j++]);\n  }\n  return result.concat(nums1.slice(i), nums2.slice(j));\n}",
    bigO: "Time O(n + m), Space O(n + m) cho mảng kết quả.",
    bigOWhy: "Mỗi phần tử được xét đúng 1 lần → O(n+m). Mảng result chứa tất cả phần tử → space tuyến tính.",
    commonMistakes: "- Quên append phần còn lại sau khi một mảng hết.\n- Dùng sort() trên concat → O((n+m) log(n+m)) thay vì O(n+m).\n- Không xử lý mảng rỗng đầu vào.",
    compareApproaches: "Two-pointer merge O(n+m) tối ưu. In-place merge từ cuối (LeetCode 88) dùng O(1) extra khi nums1 có buffer. Priority queue cho k mảng — O(N log k).",
    interviewTips: "- Viết while + hai slice còn lại — đủ cho hầu hết case.\n- Đề cập stable: dùng <= để giữ thứ tự nums1 trước nums2 khi bằng nhau.\n- Follow-up: merge in-place từ cuối mảng.",
    notes: "Đây chính là merge step trong Merge Sort — nhắc interviewer để show kiến thức liên kết.",
  },

  implement_dynamic_array: {
    title: "1.3 Mảng động (Dynamic Array)",
    meaning: "Cấu trúc mảng tự mở rộng capacity khi đầy — nền tảng của Array trong hầu hết ngôn ngữ.",
    definition: "Lưu phần tử liên tiếp trong buffer, theo dõi size (số phần tử) và capacity (chỗ tối đa). push thêm cuối O(1) amortized; get(i) O(1); pop O(1).",
    whyLearn: "Dynamic array giải thích vì sao push() JS nhanh \"như O(1)\" và vì sao đôi khi chậm đột ngột (resize). Mọi lập trình viên cần hiểu amortized analysis trước khi học linked list.",
    analogy: "Giống xe buýt nhỏ: khi đầy khách, đổi sang xe lớn gấp đôi, copy hành khách sang — đa số chuyến nhanh, thỉnh thoảng một chuyến chậm vì đổi xe.",
    algorithmSteps: "1. Khởi tạo data=[], capacity=4, size=0.\n2. push(x): nếu size==capacity thì resize (capacity*=2, copy).\n3. Gán data[size]=x, size++.\n4. pop(): giảm size, trả data[size]. get(i): kiểm tra bounds, return data[i].",
    howItWorks: "Phần tử lưu contiguous → cache-friendly, index O(1). Resize gấp đôi: tổng copy qua n lần push là n + n/2 + n/4 + ... < 2n → amortized O(1) per push.",
    dryRun: "push(1), push(2), push(3) với capacity ban đầu = 2\n\ncap=2: [1,2] size=2 FULL\nresize cap=4: [1,2,_,_]\npush(3): [1,2,3,_] size=3\npop() → 3, size=2, array [1,2,3,_]",
    visualization: "capacity vs size:\n\n  [_][_]           size=0 cap=2\n  [1][2]           size=2 cap=2  → RESIZE\n  [1][2][_][_]     size=2 cap=4\n  [1][2][3][_]     size=3 cap=4",
    codePattern: "export class DynamicArray {\n  constructor(cap = 4) { this.data = new Array(cap); this.size = 0; this.cap = cap; }\n  _resize() { const n = new Array(this.cap * 2); for (let i=0;i<this.size;i++) n[i]=this.data[i]; this.data=n; this.cap*=2; }\n  push(x) { if (this.size === this.cap) this._resize(); this.data[this.size++] = x; }\n  pop() { if (!this.size) return undefined; return this.data[--this.size]; }\n  get(i) { if (i<0||i>=this.size) throw new Error('OOB'); return this.data[i]; }\n}",
    bigO: "get O(1), push O(1) amortized, pop O(1), insert giữa O(n). Space O(n).",
    bigOWhy: "Index truy cập trực tiếp O(1). Insert giữa phải shift n phần tử. Resize hiếm (1/2, 1/4,...) → trung bình O(1) push.",
    commonMistakes: "- Nhầm size với capacity khi iterate.\n- Không copy khi resize → mất dữ liệu.\n- Quên kiểm tra bounds ở get/set.",
    compareApproaches: "Dynamic array vs Linked list: array O(1) random access, list O(1) insert đầu. JS Array đã là dynamic array — bài này học API và amortized.",
    interviewTips: "- Giải thích amortized O(1) push bằng doubling strategy.\n- Nêu cache locality advantage vs linked list.\n- Hỏi có cần insert/delete ở giữa không.",
    notes: "Khi resize, factor 2 là convention — cân bằng memory waste và tần suất resize.",
  },

  first_recurring_character: {
    title: "1.4 Ký tự lặp lại đầu tiên (First Recurring Character)",
    meaning: "Tìm ký tự xuất hiện lần thứ hai đầu tiên khi đọc chuỗi từ trái sang.",
    definition: "Duyệt chuỗi, lưu ký tự đã gặp trong Set. Ký tự đầu tiên đã có trong Set chính là đáp án.",
    whyLearn: "Bài mở đầu cho hash set/map — tra cứu O(1) thay vì quét lại O(n). Pattern này xuất hiện trong two-sum, anagram, sliding window, và deduplication.",
    analogy: "Đi chợ gặp người quen lần hai — người đầu tiên bạn nhận ra \"ủa mình gặp rồi\" chính là first recurring.",
    algorithmSteps: "1. Tạo Set seen = new Set().\n2. Duyệt từng char từ trái sang.\n3. Nếu char in seen → return char ngay.\n4. Thêm char vào seen.\n5. Hết chuỗi → return null.",
    howItWorks: "Set đảm bảo lookup O(1) average. Duyệt một lần, gặp lặp sớm nhất thì dừng — không cần đếm toàn bộ frequency trước.",
    dryRun: "Input: \"abbcde\"\n\na → seen={a}\nb → seen={a,b}\nb → ĐÃ CÓ → return \"b\"\n\nInput: \"abcdef\" → hết → null",
    visualization: "a  b  b  c  d  e\n       ↑\n   2nd b hits Set{a,b} → answer",
    codePattern: "export function firstRecurringCharacter(s) {\n  const seen = new Set();\n  for (const ch of s) {\n    if (seen.has(ch)) return ch;\n    seen.add(ch);\n  }\n  return null;\n}",
    bigO: "Time O(n), Space O(k) với k = số ký tự distinct (≤ n).",
    bigOWhy: "Một pass O(n). Set chứa tối đa k phần tử. Hash operations average O(1).",
    commonMistakes: "- Dùng indexOf trong loop → O(n²).\n- Đếm frequency hết rồi mới tìm — đúng nhưng không dừng sớm.\n- Quên case-sensitive theo đề bài.",
    compareApproaches: "Set one-pass O(n) tối ưu. Object/Map tương tự. Brute force hai vòng O(n²). Sort rồi scan O(n log n) — mất thứ tự gốc.",
    interviewTips: "- Giải thích tại sao Set không phải O(1) worst-case (hash collision).\n- Hỏi alphabet size — nếu 26 chữ cái có thể dùng mảng boolean.\n- Nêu early return khi tìm thấy.",
    notes: "Với a-z cố định: const seen = new Array(26).fill(false) — nhanh hơn Set.",
  },

  implement_hash_table: {
    title: "1.5 Bảng băm (Hash Table / HashMap)",
    meaning: "Cấu trúc map key → value với tra cứu, thêm, xóa trung bình O(1).",
    definition: "Dùng hash function chuyển key thành index bucket. Xử lý collision bằng chaining (linked list tại mỗi bucket) hoặc open addressing.",
    whyLearn: "Hash table là xương sống của cache, database index, đếm tần suất, dedup. Không hiểu hash + collision = không hiểu Map/Set/dict trong thực tế.",
    analogy: "Giống tủ locker: hash(key) cho số locker. Hai người trùng locker (collision) → xếp hàng trong cùng ô (chaining).",
    algorithmSteps: "1. Chọn số bucket m (thường power of 2 hoặc prime).\n2. hash(key) % m → index.\n3. set: thêm pair vào bucket[index].\n4. get: tìm key trong bucket.\n5. Resize khi load factor > 0.75.",
    howItWorks: "Hash phân tán key đều. Load factor α = n/m. Chaining: expected chain length α → O(1+α). Resize giữ α bounded. JS Map dùng implementation tương tự nội bộ.",
    dryRun: "set(\"name\",\"Duy\"), set(\"age\",25)\nhash(\"name\")%8=3 → buckets[3]=[[\"name\",\"Duy\"]]\nhash(\"age\")%8=1 → buckets[1]=[[\"age\",25]]\nget(\"name\") → duyệt bucket 3 → \"Duy\"",
    visualization: "buckets:\n[0]: []\n[1]: age→25\n[2]: []\n[3]: name→Duy\n[4]: []",
    codePattern: "export class HashMap {\n  constructor(size=16) { this.buckets = Array.from({length:size},()=>[]); this.size=size; }\n  _hash(k){ let h=0; for(const c of String(k)) h=(h*31+c.charCodeAt(0))%this.size; return h; }\n  set(k,v){ const i=this._hash(k); const b=this.buckets[i]; const f=b.find(([key])=>key===k); if(f)f[1]=v; else b.push([k,v]); }\n  get(k){ return this.buckets[this._hash(k)].find(([key])=>key===k)?.[1]; }\n  has(k){ return this.get(k)!==undefined; }\n}",
    bigO: "Average O(1) get/set/delete; Worst O(n) nếu all keys collide. Space O(n+m).",
    bigOWhy: "Hash O(|key|), bucket scan O(α) average. Worst: mọi key cùng bucket → O(n). Resize O(n) nhưng amortized.",
    commonMistakes: "- Hash quá yếu → nhiều collision.\n- Quên resize → chains dài, chậm.\n- So sánh object key bằng reference thay vì value equality.",
    compareApproaches: "Chaining vs open addressing: chaining đơn giản khi delete; open addressing cache-friendly hơn. JS Map — dùng khi key phức tạp.",
    interviewTips: "- Nêu load factor và resize strategy.\n- Giải thích worst case và khi nào xảy ra.\n- Biết JS object khác Map (key chỉ string/symbol).",
    notes: "Interview thường yêu cầu chaining + linked list tại bucket — implement đủ set/get/has/delete.",
  },

  singly_linked_list: {
    title: "2.1 Danh sách liên kết đơn (Singly Linked List)",
    meaning: "Chuỗi node: mỗi node chứa value và con trỏ next tới node kế — không lưu contiguous như array.",
    definition: "Head trỏ node đầu. Insert đầu O(1). Tìm theo index O(n). Không random access. Dùng khi cần insert/delete đầu thường xuyên.",
    whyLearn: "Linked list là nền tảng cho stack, queue, hash chaining, và nhiều cấu trúc nâng cao. Hiểu pointer manipulation giúp bạn reverse list, detect cycle, merge lists — classic interview.",
    analogy: "Giống chuỗi toa tàu: mỗi toa biết toa sau, không biết toa trước. Muốn đến toa 5 phải đi qua 1→2→3→4.",
    algorithmSteps: "1. Định nghĩa class Node { value, next }.\n2. Class SinglyLinkedList { head, tail, length }.\n3. prepend: node mới.next = head; head = node.\n4. append: tail.next = node; tail = node.\n5. insert/delete: duyệt tới index-1, nối con trỏ.",
    howItWorks: "Mỗi thao tác chỉ đổi vài con trỏ — không shift như array. Trade-off: O(n) traverse để tìm vị trí. Tail pointer giúp append O(1).",
    dryRun: "prepend(3), prepend(2), append(4)\n\nprepend(3): head→3\nprepend(2): head→2→3\nappend(4): head→2→3→4, tail=4\ninsert(1,99): head→2→99→3→4",
    visualization: "head\n ↓\n[2|•]→[99|•]→[3|•]→[4|null]\n\nprepend: new→head\nappend: tail.next=new",
    codePattern: "class Node { constructor(v){ this.value=v; this.next=null; } }\nexport class SinglyLinkedList {\n  constructor(){ this.head=null; this.tail=null; this.length=0; }\n  prepend(v){ const n=new Node(v); if(!this.head){this.head=this.tail=n;} else { n.next=this.head; this.head=n; } this.length++; }\n  append(v){ const n=new Node(v); if(!this.tail){this.head=this.tail=n;} else { this.tail.next=n; this.tail=n; } this.length++; }\n}",
    bigO: "prepend/append O(1) với tail, get/insert/delete tại index O(n). Space O(n).",
    bigOWhy: "Không index trực tiếp — phải walk từ head. Mỗi node O(1) extra pointer.",
    commonMistakes: "- Mất reference head khi insert.\n- Quên cập nhật tail khi append/delete cuối.\n- Off-by-one khi tìm node trước vị trí insert.",
    compareApproaches: "Singly vs doubly: singly ít memory, khó delete cuối O(n). Array: O(1) access, O(n) insert giữa.",
    interviewTips: "- Vẽ pointer trước khi code.\n- Dùng dummy node cho delete/insert phức tạp.\n- Luôn handle list rỗng và 1 node.",
    notes: "Nhớ this.head và this.tail — nhiều bug đến từ tail không được cập nhật.",
  },

  doubly_linked_list: {
    title: "2.2 Danh sách liên kết đôi (Doubly Linked List)",
    meaning: "Mỗi node có prev và next — duyệt được cả hai chiều, delete node đã biết con trỏ O(1).",
    definition: "Node { value, prev, next }. Head/tail cho đầu cuối. Insert sau node known O(1). Browser history, LRU cache dùng biến thể DLL.",
    whyLearn: "DLL cho phép O(1) delete khi đã có node reference — critical cho LRU Cache (LeetCode 146). Hiểu prev/next giúp implement deque, undo/redo.",
    analogy: "Giống hành lang hai chiều: mỗi phòng có cửa trước và cửa sau. Từ phòng bất kỳ, đi được cả lùi lẫn tiến.",
    algorithmSteps: "1. Node { value, prev, next }.\n2. prepend: nối head.prev, head = n.\n3. append: nối tail.next, tail = n.\n4. remove(node): node.prev.next = node.next; node.next.prev = node.prev.\n5. Cập nhật head/tail nếu xóa đầu/cuối.",
    howItWorks: "Hai con trỏ cho phép unlink node mà không cần tìm predecessor — chỉ cần reference tới node. Trade-off: thêm memory cho prev pointer.",
    dryRun: "append(1), append(2), prepend(0)\n\nhead→0↔1↔2←tail\nremove(1): head→0↔2←tail",
    visualization: "null←[0]↔[1]↔[2]→null\n      head      tail",
    codePattern: "class Node { constructor(v){ this.value=v; this.prev=this.next=null; } }\nexport class DoublyLinkedList {\n  constructor(){ this.head=this.tail=null; }\n  append(v){ const n=new Node(v); if(!this.tail){this.head=this.tail=n;} else { n.prev=this.tail; this.tail.next=n; this.tail=n; } }\n  remove(node){ if(node.prev) node.prev.next=node.next; else this.head=node.next; if(node.next) node.next.prev=node.prev; else this.tail=node.prev; }\n}",
    bigO: "insert/delete với node ref O(1), index access O(n). Space O(n) + extra prev pointers.",
    bigOWhy: "Biết node → unlink 4 pointer assignments O(1). Không biết vị trí → vẫn phải walk O(n).",
    commonMistakes: "- Quên set prev khi append/prepend.\n- Không handle remove head/tail edge cases.\n- Memory leak: không nullify removed node pointers.",
    compareApproaches: "DLL vs SLL: DLL tốn memory hơn nhưng delete linh hoạt. vs Array: DLL tốt cho frequent insert/delete tại known position.",
    interviewTips: "- LRU Cache follow-up: hash map + DLL.\n- Vẽ 4 arrow khi remove node.\n- Sentinel/dummy head+tail đơn giản hóa edge cases.",
    notes: "Khi remove, luôn kiểm tra node === head hoặc node === tail.",
  },

  reverse_linked_list: {
    title: "2.3 Đảo ngược linked list (Reverse Linked List)",
    meaning: "Đổi hướng tất cả con trỏ next — node cuối thành head.",
    definition: "Cho head, trả về head mới của list đã reverse. Iterative: 3 con trỏ prev, curr, next. Recursive: reverse phần sau rồi gắn.",
    whyLearn: "Bài kinh điển test pointer skills. Pattern reverse sublist, k-group reverse, palindrome list đều dựa trên bài này.",
    analogy: "Giống đảo chiều toa tàu: mỗi toa trước nối với toa sau, giờ toa sau nối ngược lại toa trước.",
    algorithmSteps: "1. prev = null, curr = head.\n2. While curr: lưu next = curr.next; curr.next = prev; prev = curr; curr = next.\n3. Return prev (head mới).\n4. Recursive: base null/1 node; reverse rest; head.next.next = head; head.next = null.",
    howItWorks: "Iterative lật từng mũi tên một. Mỗi bước curr trỏ ngược về prev. Cuối cùng prev ở node cuối cũ.",
    dryRun: "1→2→3→null\n\nprev=null, curr=1: 1→null, prev=1, curr=2\nprev=1, curr=2: 2→1→null, prev=2, curr=3\nprev=2, curr=3: 3→2→1→null, prev=3, curr=null\nreturn 3",
    visualization: "Before: 1→2→3→null\nStep:   null←1  2→3\nAfter:  3→2→1→null",
    codePattern: "export function reverseLinkedList(head) {\n  let prev = null, curr = head;\n  while (curr) {\n    const next = curr.next;\n    curr.next = prev;\n    prev = curr;\n    curr = next;\n  }\n  return prev;\n}",
    bigO: "Time O(n), Space O(1) iterative; O(n) stack recursive.",
    bigOWhy: "Duyệt mỗi node 1 lần. Iterative chỉ 3 con trỏ. Recursive: n stack frames.",
    commonMistakes: "- Mất next trước khi gán curr.next = prev.\n- Return head cũ thay vì prev.\n- Recursive: quên head.next = null → cycle.",
    compareApproaches: "Iterative O(1) space — preferred interview. Recursive elegant nhưng stack O(n). Dùng stack push all rồi pop — O(n) space, không cần pointer skill.",
    interviewTips: "- Viết iterative trước, offer recursive.\n- Vẽ 3 con trỏ trên giấy.\n- Follow-up: reverse between m and n.",
    notes: "Luôn lưu next = curr.next TRƯỚC khi đổi curr.next.",
  },

  implement_stack: {
    title: "2.4 Stack (Ngăn xếp)",
    meaning: "LIFO — Last In First Out. Push/pop từ cùng một đầu (top).",
    definition: "push(x) thêm top, pop() lấy và xóa top, peek() xem top không xóa. Dùng cho undo, DFS, bracket matching, expression eval.",
    whyLearn: "Stack là ADT nền tảng cho DFS, backtracking, monotonic stack, và call stack hiểu recursion. Mọi senior engineer cần implement stack từ scratch.",
    analogy: "Chồng đĩa: đĩa cuối đặt lên sẽ được lấy xuống trước. Không thể lấy đĩa ở giữa mà không động đĩa trên.",
    algorithmSteps: "1. Lưu items trong array hoặc linked list.\n2. push: thêm cuối array (top).\n3. pop: lấy và xóa phần tử cuối.\n4. peek: return items[length-1].\n5. isEmpty: length === 0.",
    howItWorks: "Array implementation: push/pop cuối O(1) amortized. Linked list: push/pop đầu O(1). Chỉ thao tác một đầu — đơn giản hơn queue.",
    dryRun: "push(1), push(2), push(3)\nstack: [1,2,3] top=3\npop()→3, stack [1,2]\npeek()→2",
    visualization: "  top → [3]\n        [2]\n        [1]\n        ---",
    codePattern: "export class Stack {\n  constructor(){ this.items=[]; }\n  push(x){ this.items.push(x); }\n  pop(){ if(this.isEmpty()) throw new Error('empty'); return this.items.pop(); }\n  peek(){ return this.items[this.items.length-1]; }\n  isEmpty(){ return this.items.length===0; }\n}",
    bigO: "push/pop/peek O(1) amortized với array. Space O(n).",
    bigOWhy: "Chỉ thao tác phần tử cuối — không shift. Array resize hiếm → amortized O(1).",
    commonMistakes: "- pop khi empty không check → undefined.\n- Nhầm stack với queue (FIFO).\n- Dùng shift() cho pop → O(n).",
    compareApproaches: "Array vs linked list stack: array đơn giản, cache-friendly. Linked list O(1) strict, no resize spike.",
    interviewTips: "- Nêu LIFO và 2-3 use cases thực tế.\n- Valid parentheses là classic stack bài.\n- Monotonic stack — mention nếu level senior.",
    notes: "JS array push/pop ở cuối — perfect cho stack.",
  },

  implement_queue: {
    title: "2.5 Queue (Hàng đợi)",
    meaning: "FIFO — First In First Out. Enqueue cuối, dequeue đầu.",
    definition: "enqueue(x) thêm rear, dequeue() lấy front. Dùng cho BFS, task scheduling, buffer, printer queue.",
    whyLearn: "Queue là engine của BFS — tìm shortest path unweighted. Hiểu queue + BFS là bắt buộc cho graph/tree interview.",
    analogy: "Xếp hàng mua vé: người vào trước được phục vụ trước. Không chen ngang được.",
    algorithmSteps: "1. Dùng linked list (head=front, tail=rear) hoặc two-pointer array.\n2. enqueue: thêm rear, cập nhật tail.\n3. dequeue: lấy front, head = head.next.\n4. peek front, isEmpty check.\n5. Tránh shift() trên JS array — O(n).",
    howItWorks: "Linked list: enqueue O(1) tại tail, dequeue O(1) tại head. Circular buffer: O(1) cả hai với fixed capacity.",
    dryRun: "enqueue(1), enqueue(2), enqueue(3)\nfront→1→2→3←rear\ndequeue()→1, front→2\npeek()→2",
    visualization: "  FRONT → [1][2][3] ← REAR\n  dequeue lấy 1, enqueue(4) thêm cuối",
    codePattern: "class QNode { constructor(v){ this.value=v; this.next=null; } }\nexport class Queue {\n  constructor(){ this.head=this.tail=null; }\n  enqueue(v){ const n=new QNode(v); if(!this.tail){this.head=this.tail=n;} else { this.tail.next=n; this.tail=n; } }\n  dequeue(){ if(!this.head) return undefined; const v=this.head.value; this.head=this.head.next; if(!this.head)this.tail=null; return v; }\n}",
    bigO: "enqueue/dequeue O(1) với linked list. Space O(n).",
    bigOWhy: "Head/tail pointers — không cần shift cả mảng. Array+shift là O(n) per dequeue.",
    commonMistakes: "- Dùng array.shift() → O(n) mỗi dequeue.\n- Quên set tail=null khi dequeue hết queue.\n- Nhầm front/rear.",
    compareApproaches: "Linked list queue vs two stacks (MyQueue) vs circular buffer. BFS dùng queue — never stack.",
    interviewTips: "- Giải thích tại sao không dùng array.shift.\n- BFS template dùng queue — connect concepts.\n- Follow-up: implement với 2 stacks.",
    notes: "Trong BFS: queue.push neighbor, shift/process front — hoặc dùng index pointer trên array.",
  },

  queue_using_stacks: {
    title: "2.6 Queue bằng hai Stack (Queue using Stacks)",
    meaning: "Mô phỏng FIFO queue chỉ dùng hai LIFO stack.",
    definition: "stackIn nhận enqueue. stackOut phục vụ dequeue. Khi stackOut rỗng, pour stackIn sang stackOut (đảo thứ tự → FIFO).",
    whyLearn: "Bài classic về amortized analysis và chuyển đổi giữa ADT. Amazon/Google hay hỏi — test hiểu invariant và lazy transfer.",
    analogy: "Hai chồng đĩa: đĩa mới vào chồng A. Khi phục vụ, đổ cả chồng A sang chồng B — đĩa dưới cùng A giờ trên cùng B, ra đúng thứ tự FIFO.",
    algorithmSteps: "1. Khởi tạo inStack=[], outStack=[].\n2. push(x): inStack.push(x).\n3. peek/pop: nếu outStack rỗng, pour inStack→outStack.\n4. pop từ outStack.\n5. empty: cả hai stack rỗng.",
    howItWorks: "Pour đảo thứ tự 2 lần = giữ thứ tự gốc. Mỗi phần tử chỉ moved tối đa 2 lần → amortized O(1) per operation.",
    dryRun: "push(1), push(2), push(3)\nin=[1,2,3], out=[]\npop(): pour → in=[], out=[3,2,1], pop→1\npush(4): in=[4]\npop(): out=[3,2], pop→3 (không pour)",
    visualization: "inStack: [1,2,3]  --pour-->  outStack: [3,2,1]\n                              pop → 1 (FIFO order)",
    codePattern: "export class MyQueue {\n  constructor(){ this.in=[]; this.out=[]; }\n  _pour(){ while(this.in.length) this.out.push(this.in.pop()); }\n  push(x){ this.in.push(x); }\n  pop(){ if(!this.out.length) this._pour(); return this.out.pop(); }\n  peek(){ if(!this.out.length) this._pour(); return this.out[this.out.length-1]; }\n}",
    bigO: "push O(1), pop/peek amortized O(1), worst single pop O(n) khi pour.",
    bigOWhy: "Pour O(n) nhưng mỗi element poured ≤1 lần giữa 2 pops → amortized O(1).",
    commonMistakes: "- Pour mỗi pop → vẫn đúng nhưng không cần thiết.\n- Pour khi outStack không rỗng → hỏng thứ tự.\n- Quên empty check.",
    compareApproaches: "2 stacks amortized O(1) vs linked list queue O(1) strict. 2 stacks tiết kiệm nếu chỉ có stack API.",
    interviewTips: "- Giải thích amortized analysis — điểm cộng lớn.\n- Viết _pour helper private.\n- Follow-up: stack using 2 queues (khó hơn).",
    notes: "Chỉ pour khi outStack empty — invariant quan trọng nhất.",
  },

  bst_operations: {
    title: "3.1 Binary Search Tree — Insert & Lookup",
    meaning: "Cây nhị phân tìm kiếm: trái < node < phải — hỗ trợ insert/lookup O(log n) khi cân bằng.",
    definition: "Mỗi node có value, left, right. Insert: đi trái nếu nhỏ hơn, phải nếu lớn hơn. Lookup: so sánh tương tự. Inorder traversal cho sorted order.",
    whyLearn: "BST là bridge từ array binary search sang tree structures. Là nền cho balanced trees (AVL, Red-Black), sets/maps (TreeMap), và database indexes.",
    analogy: "Giống tra từ điển: mở giữa, nếu từ cần tìm nhỏ hơn thì lật nửa trái, lớn hơn thì nửa phải — mỗi bước loại bỏ một nửa.",
    algorithmSteps: "1. Node { value, left, right }.\n2. insert(val): nếu !root thì root=node; else recursive compare.\n3. lookup(val): null → not found; equal → found; else trái/phải.\n4. Inorder: left → node → right.\n5. Remove (nâng cao): 0/1 child thay thế; 2 children lấy inorder successor.",
    howItWorks: "Tính chất BST: mọi node trái < root < mọi node phải. Mỗi level loại ~một nửa không gian tìm kiếm — giống binary search trên sorted array nhưng dynamic.",
    dryRun: "insert 9,4,6,20,170,11\n\nroot=9\n4<9 → left, 6>4 → right of 4\n20>9 → right, 170>20 → right\nlookup(6): 9→4→6 FOUND\nlookup(100): NOT FOUND",
    visualization: "        9\n       / \\\n      4   20\n       \\  /  \\\n        6 11  170\n\ninsert(6): 9→4→right child",
    codePattern: "class Node { constructor(v){ this.value=v; this.left=this.right=null; } }\nexport class BST {\n  constructor(){ this.root=null; }\n  insert(v, node=this.root){ if(!node){ const n=new Node(v); if(!this.root)this.root=n; return n; } if(v<node.value) return node.left?this.insert(v,node.left):(node.left=new Node(v)); if(v>node.value) return node.right?this.insert(v,node.right):(node.right=new Node(v)); return node; }\n  lookup(v, node=this.root){ if(!node) return null; if(v===node.value) return node; return v<node.value?this.lookup(v,node.left):this.lookup(v,node.right); }\n}",
    bigO: "Average O(log n) insert/lookup; Worst O(n) skewed tree. Space O(n).",
    bigOWhy: "Balanced: mỗi bước giảm một nửa → log n levels. Skewed (insert sorted data): thành linked list O(n).",
    commonMistakes: "- Cho phép duplicate không rõ policy (trái hay phải).\n- Quên return node khi recursive insert.\n- Nhầm BST với binary tree thường.",
    compareApproaches: "BST vs HashMap: BST sorted order + range query; Hash O(1) average. vs Array sorted: BST dynamic insert O(log n) vs array insert O(n).",
    interviewTips: "- Luôn nêu worst case O(n) skewed.\n- Follow-up: validate BST, kth smallest.\n- Nhắc inorder = sorted output.",
    notes: "Visualgo BST visualization rất hữu ích cho insert/delete. Remove node là phần khó — practice riêng.",
  },

  min_heap_operations: {
    title: "3.2 Min Heap — Insert & Extract Min",
    meaning: "Complete binary tree: parent ≤ children. Min ở root — extract O(log n).",
    definition: "Lưu bằng array: parent(i)=(i-1)/2, left=2i+1, right=2i+2. insert: thêm cuối, bubble up. extractMin: swap root-leaf, bubble down.",
    whyLearn: "Heap là core của priority queue, Dijkstra, heap sort, Top K problems. Hiểu heapify giúp giải running median, merge k sorted lists.",
    analogy: "Giống tổ chức công ty: sếp (min) ở trên, mỗi quản lý nhỏ hơn cấp dưới. Nhân viên mới vào đúng chỗ bằng cách 'thăng chức' hoặc 'xuống cấp'.",
    algorithmSteps: "1. Array heap[], size.\n2. insert(x): heap.push(x); bubbleUp(last index).\n3. bubbleUp: swap với parent nếu nhỏ hơn parent.\n4. extractMin: swap root và last; pop; bubbleDown(0).\n5. bubbleDown: swap với child nhỏ hơn.",
    howItWorks: "Complete tree property → array compact, no pointers. Heap property local: fix chỉ cần O(log n) comparisons along one root-to-leaf or leaf-to-root path.",
    dryRun: "insert 5,3,7,1\n\n[5]→[3,5] bubble 3 up→[3,5]→[3,5,7]→[1,3,5,7] bubble 1 up\nextractMin: swap 1↔7, pop→[7,3,5], bubbleDown→[3,7,5]",
    visualization: "Array: [1, 3, 5, 7]\nTree:\n    1\n   / \\\n  3   5\n /\n7",
    codePattern: "export class MinHeap {\n  constructor(){ this.heap=[]; }\n  insert(v){ this.heap.push(v); this._bubbleUp(this.heap.length-1); }\n  extractMin(){ const min=this.heap[0]; const last=this.heap.pop(); if(this.heap.length){ this.heap[0]=last; this._bubbleDown(0); } return min; }\n  _bubbleUp(i){ while(i>0){ const p=(i-1>>1); if(this.heap[i]>=this.heap[p]) break; [this.heap[i],this.heap[p]]=[this.heap[p],this.heap[i]]; i=p; } }\n}",
    bigO: "insert/extractMin O(log n), peek min O(1), build heap O(n). Space O(n).",
    bigOWhy: "Tree height log n. Bubble up/down 1 path. buildHeap bottom-up O(n) — không phải n insert.",
    commonMistakes: "- Sai công thức parent/child index.\n- bubbleDown so sánh sai child (phải chọn min child).\n- Quên handle empty heap extract.",
    compareApproaches: "Min heap vs sorted array: insert O(log n) vs O(n). vs BST: heap chỉ care min/max, không full sort. Priority queue = heap.",
    interviewTips: "- Viết index formulas trước khi code.\n- Top K elements = min heap size K.\n- Mention max heap = negate values.",
    notes: "0-indexed: parent=(i-1)>>1, left=2*i+1, right=2*i+2.",
  },

  implement_trie: {
    title: "3.3 Trie (Prefix Tree)",
    meaning: "Cây ký tự — mỗi node đại diện prefix, tra cứu từ/autocomplete O(m) với m = độ dài key.",
    definition: "Root rỗng. Mỗi node có children map và isEndOfWord. insert word từng char. search prefix bằng cách đi theo char.",
    whyLearn: "Trie dominate autocomplete, spell checker, IP routing, word search II. Không phụ thuộc số lượng từ n — chỉ độ dài từ — critical cho large dictionaries.",
    analogy: "Giống cây thư mục theo chữ cái: folder 'c'→'a'→'t' kết thúc file 'cat'. Tìm mọi từ bắt đầu 'ca' = mở folder c rồi a.",
    algorithmSteps: "1. TrieNode { children: Map, isEnd: false }.\n2. insert(word): duyệt char, tạo node nếu thiếu, isEnd=true ở cuối.\n3. search(word): đi hết + check isEnd.\n4. startsWith(prefix): đi hết prefix, không cần isEnd.\n5. Optional: count, delete (prune).",
    howItWorks: "Shared prefixes → tiết kiệm space vs storing m words separately. Lookup không binary search — direct child pointer per char.",
    dryRun: "insert \"cat\", \"car\", \"dog\"\n\nroot→c→a→t(isEnd)\n          →r(isEnd)\n     →d→o→g(isEnd)\nsearch(\"car\"): c→a→r isEnd ✓\nstartsWith(\"ca\"): c→a ✓",
    visualization: "root\n └c─a─┬t*\n      └r*\n └d─o─g*\n(* = end of word)",
    codePattern: "class TrieNode { constructor(){ this.children=new Map(); this.isEnd=false; } }\nexport class Trie {\n  constructor(){ this.root=new TrieNode(); }\n  insert(w){ let n=this.root; for(const c of w){ if(!n.children.has(c)) n.children.set(c,new TrieNode()); n=n.children.get(c); } n.isEnd=true; }\n  search(w){ const n=this._walk(w); return !!n&&n.isEnd; }\n  startsWith(p){ return !!this._walk(p); }\n  _walk(s){ let n=this.root; for(const c of s){ if(!n.children.has(c)) return null; n=n.children.get(c); } return n; }\n}",
    bigO: "insert/search/startsWith O(m) time, m = key length. Space O(ALPHABET * N * m) worst.",
    bigOWhy: "Đi từng ký tự 1 lần — không scan N words. Space: mỗi char có thể tạo node mới.",
    commonMistakes: "- Quên set isEnd khi insert.\n- search không check isEnd (nhầm prefix với full word).\n- Dùng object thay Map — key 'length' conflict.",
    compareApproaches: "Trie vs HashSet: trie hỗ trợ prefix search. vs BST on strings: trie O(m) vs O(m log n). Array sort + binary search cho single lookup.",
    interviewTips: "- Implement startsWith — autocomplete follow-up.\n- Word Search II = trie + backtracking.\n- Nêu space trade-off với hash set.",
    notes: "Dùng Map cho children — an toàn hơn object literal trong JS.",
  },

  avl_tree: {
    title: "3.4 AVL Tree (Self-Balancing BST)",
    meaning: "BST tự cân bằng: |balance factor| ≤ 1 mọi node — đảm bảo O(log n) operations.",
    definition: "Balance factor = height(left) - height(right). Sau insert/delete, nếu imbalance thì rotate (LL, RR, LR, RL). Lưu height mỗi node.",
    whyLearn: "AVL giải thích tại sao cần balanced trees khi data sorted insert vào BST thường. Foundation cho Red-Black trees trong std::map, Java TreeMap.",
    analogy: "Giống cân đối đũa: nếu một bên nặng hơn 1 đĩa, xoay để cân lại — cây không bị 'nghiêng' thành linked list.",
    algorithmSteps: "1. BST insert thông thường.\n2. Cập nhật height từ node ngược lên root.\n3. Tính balance factor.\n4. Nếu |bf|>1: xác định LL/RR/LR/RL case.\n5. Rotate single hoặc double để rebalance.",
    howItWorks: "Single rotation (LL/RR): 1 pivot. Double (LR/RL): 2 rotations. Sau rotate, BST property + balance restored. Height O(log n) guaranteed.",
    dryRun: "insert 10,20,30 (RR case)\n\n10→20 skew right\nrotate left at 10:\n    20\n   /  \\\n 10   30",
    visualization: "RR case (right-right heavy):\n  10              20\n    \\            /  \\\n     20   →    10   30\n       \\\n        30",
    codePattern: "export class AVLTree {\n  insert(v){ this.root = this._insert(this.root, v); }\n  _insert(node, v){ /* BST insert + update height + rotate if imbalance */ }\n  _rotateLeft(z){ /* RR: pivot right child up */ }\n  _rotateRight(z){ /* LL */ }\n  _balance(node){ /* check bf, rotate */ }\n}",
    bigO: "insert/delete/search O(log n) guaranteed. Space O(n).",
    bigOWhy: "Height bounded by ~1.44 log n — mọi operation theo height. Rotation O(1) local work.",
    commonMistakes: "- Quên update height sau rotate.\n- Nhầm LR vs RL rotation order.\n- Chỉ rotate tại leaf không propagate lên ancestor.",
    compareApproaches: "AVL vs Red-Black: AVL stricter balance, faster lookup; RB fewer rotations, faster insert. vs unbalanced BST: AVL worst-case guarantee.",
    interviewTips: "- Biết 4 rotation cases — vẽ trước khi code.\n- Interview thường hỏi concept hơn full implementation.\n- Nêu khi nào cần guaranteed O(log n).",
    notes: "Full AVL implementation dài — focus insert + LL/RR trước. Visualgo AVL rất hữu ích.",
  },

  build_adjacency_list: {
    title: "4.1 Xây dựng Adjacency List (Đồ thị)",
    meaning: "Biểu diễn đồ thị: mỗi node map tới danh sách neighbor — chuẩn cho sparse graphs.",
    definition: "Cho edges [[u,v],...], tạo Map hoặc object: graph[u] = [neighbors]. Có thể directed hoặc undirected (thêm cả 2 chiều).",
    whyLearn: "Adjacency list là input format cho BFS, DFS, Dijkstra, topological sort. Không biết build graph = không làm được 80% graph interview.",
    analogy: "Danh bạ điện thoại: mỗi người (node) có list bạn bè (neighbors) — tra nhanh ai kết nối với ai.",
    algorithmSteps: "1. Khởi tạo graph = Map hoặc {}.\n2. Với mỗi edge [u,v]:\n3. Nếu undirected: thêm v vào graph[u], u vào graph[v].\n4. Nếu directed: chỉ v vào graph[u].\n5. Đảm bảo node không có edge vẫn có entry rỗng (optional).",
    howItWorks: "List chỉ lưu edges thực — space O(V+E). Tra neighbor của u: O(degree(u)). Phù hợp sparse graph. Dense graph có thể dùng adjacency matrix O(V²).",
    dryRun: "edges=[[0,1],[0,2],[1,2]] undirected\n\ngraph[0]=[1,2]\ngraph[1]=[0,2]\ngraph[2]=[0,1]",
    visualization: "  0 --- 1\n  |   / |\n  |  /  |\n  2 -----+\n\nAdj list:\n0: [1,2]\n1: [0,2]\n2: [0,1]",
    codePattern: "export function buildAdjacencyList(edges, directed=false) {\n  const graph = new Map();\n  const add = (a,b) => { if(!graph.has(a)) graph.set(a,[]); graph.get(a).push(b); };\n  for (const [u,v] of edges) { add(u,v); if(!directed) add(v,u); }\n  return graph;\n}",
    bigO: "Build O(E), Space O(V+E).",
    bigOWhy: "Duyệt mỗi edge 1-2 lần. Mỗi edge stored once (undirected: twice).",
    commonMistakes: "- Directed vs undirected nhầm.\n- Node isolated không có trong map → BFS miss.\n- Duplicate edges không dedup.",
    compareApproaches: "Adjacency list O(V+E) space vs matrix O(V²). List tốt sparse; matrix O(1) edge lookup.",
    interviewTips: "- Hỏi directed/weighted ngay đầu.\n- Dùng Set cho neighbors nếu cần dedup.\n- Template cho mọi graph bài sau.",
    notes: "Luôn clarify undirected vs directed với interviewer trước khi code.",
  },

  graph_bfs: {
    title: "4.2 Breadth-First Search (BFS) trên đồ thị",
    meaning: "Duyệt đồ thị theo tầng — Queue FIFO, tìm shortest path unweighted.",
    definition: "Từ start, enqueue start, mark visited. Dequeue node, xử lý, enqueue unvisited neighbors. Level-order trên tree là BFS đặc biệt.",
    whyLearn: "BFS = shortest path unweighted, level-order traversal, multi-source BFS, word ladder. Một trong hai thuật toán graph quan trọng nhất.",
    analogy: "Sóng nước lan từ viên sỏi ném xuống hồ — loang đều theo vòng tròn trước khi đi sâu. Hoặc tìm chìa khoá: quét hết tầng 1 rồi mới lên tầng 2.",
    algorithmSteps: "1. queue=[start], visited={start}.\n2. While queue không rỗng: node=dequeue.\n3. Process node (add to result / check goal).\n4. For neighbor in graph[node]: if !visited, mark + enqueue.\n5. Return result hoặc distance map.",
    howItWorks: "Queue đảm bảo nodes theo distance tăng dần từ start. Lần đầu reach target = shortest hops. visited tránh cycle và redundant work.",
    dryRun: "Tree: 9→4,20→1,5,9,170\n\nqueue: [9] → visit 9\nqueue: [4,20] → visit 4,20\nqueue: [1,5,9,170]\noutput: [9,4,20,1,5,9,170]",
    visualization: "        9        ← level 0\n    4       20   ← level 1\n  1  5   9  170  ← level 2\n\nBFS: 9,4,20,1,5,9,170",
    codePattern: "export function bfs(graph, start) {\n  const q=[start], visited=new Set([start]), order=[];\n  while(q.length){\n    const node=q.shift();\n    order.push(node);\n    for(const nb of graph.get(node)||[]){\n      if(!visited.has(nb)){ visited.add(nb); q.push(nb); }\n    }\n  }\n  return order;\n}",
    bigO: "Time O(V+E), Space O(V) cho queue + visited.",
    bigOWhy: "Mỗi vertex và edge xét tối đa 1 lần. Queue chứa tối đa V nodes.",
    commonMistakes: "- Quên mark visited KHI enqueue (không phải khi dequeue) — duplicate queue.\n- Dùng stack thay queue → thành DFS.\n- Không handle disconnected components.",
    compareApproaches: "BFS shortest unweighted vs DFS không guarantee shortest. BFS vs Dijkstra: BFS khi edge weight = 1.",
    interviewTips: "- Code cả iterative (queue) và mention recursive không natural cho BFS.\n- Multi-source BFS: enqueue all sources.\n- Grid BFS: 4-directional neighbors.",
    notes: "Mark visited at enqueue time — classic bug if marked at dequeue.",
  },

  graph_dfs: {
    title: "4.3 Depth-First Search (DFS) trên đồ thị",
    meaning: "Duyệt sâu nhất có thể trước khi backtrack — Stack hoặc recursion.",
    definition: "Từ start, đi sâu neighbor chưa visit, khi hết đường thì quay lại (backtrack). Dùng cho cycle detect, topological sort, connected components.",
    whyLearn: "DFS cho path exploration, maze solving, cycle detection, strongly connected components. Complement BFS — nhiều bài chỉ giải được bằng DFS.",
    analogy: "Đi mê cung: chọn một hướng, đi tới cuối đường cụt, quay lại ngã rẽ trước đó thử hướng khác — giống backtracking.",
    algorithmSteps: "1. visited = Set.\n2. function dfs(node): mark visited, process.\n3. For neighbor: if !visited, dfs(neighbor).\n4. Gọi dfs(start) hoặc loop all nodes (disconnected).\n5. Iterative: stack push start, pop, push unvisited neighbors.",
    howItWorks: "Recursion implicit stack. Đi sâu trước → memory O(depth) vs BFS O(width). Phù hợp khi cần explore all paths hoặc detect back-edge (cycle).",
    dryRun: "Same tree 9,4,20,1,5,9,170\n\nDFS preorder: 9→4→1→5→20→9→170\n(backtrack sau mỗi leaf)",
    visualization: "        9\n       / \\\n      4   20\n     /\\   /\\\n    1 5  9 170\n\nDFS path: 9→4→1, back, 5, back, 20→9, 170",
    codePattern: "export function dfs(graph, start) {\n  const visited=new Set(), order=[];\n  function go(u){ visited.add(u); order.push(u); for(const v of graph.get(u)||[]) if(!visited.has(v)) go(v); }\n  go(start); return order;\n}",
    bigO: "Time O(V+E), Space O(V) visited + O(depth) recursion stack.",
    bigOWhy: "Mỗi vertex/edge 1 lần. Stack depth = longest path.",
    commonMistakes: "- Quên handle disconnected graph (loop all nodes).\n- Không mark visited trước khi recurse → infinite loop có cycle.\n- Nhầm DFS order với BFS order.",
    compareApproaches: "DFS vs BFS: DFS less memory on wide graphs; BFS shortest path. Iterative DFS dùng explicit stack.",
    interviewTips: "- Biết 3 tree traversals đều là DFS variants.\n- Cycle detect: directed cần 3-color; undirected check parent.\n- Topological sort = DFS finish time reverse.",
    notes: "Grid DFS: 4 hoặc 8 directions, mark visited in-place hoặc Set.",
  },

  factorial: {
    title: "5.1 Giai thừa (Factorial) — Đệ quy",
    meaning: "n! = n × (n-1) × ... × 1. Base case: 0! = 1! = 1.",
    definition: "factorial(n) = n * factorial(n-1) khi n > 1; return 1 khi n <= 1. Mô hình đệ quy cơ bản nhất.",
    whyLearn: "Factorial là hello world của recursion — học base case, recursive case, call stack trước khi vào tree/graph DFS phức tạp.",
    analogy: "Giống đồng hồ đếm ngược pháo hoa: 5! = 5 chờ 4! xong, 4! chờ 3!... cho đến 1! dừng.",
    algorithmSteps: "1. Base case: if n <= 1 return 1.\n2. Recursive: return n * factorial(n - 1).\n3. Hoặc iterative: result=1, for i=2..n result*=i.\n4. Handle negative n → error hoặc undefined.\n5. Trace call stack để hiểu.",
    howItWorks: "Mỗi call chờ sub-call return. Stack: factorial(4) → factorial(3) → factorial(2) → factorial(1) → unwind 2,6,24.",
    dryRun: "factorial(4)\n\nfactorial(4) = 4 * factorial(3)\n  factorial(3) = 3 * factorial(2)\n    factorial(2) = 2 * factorial(1)\n      factorial(1) = 1  ← base\n    = 2 * 1 = 2\n  = 3 * 2 = 6\n= 4 * 6 = 24",
    visualization: "Call stack unwind:\nf(4)\n └f(3)\n   └f(2)\n     └f(1)→1\n     ←2\n   ←6\n ←24",
    codePattern: "export function factorial(n) {\n  if (n <= 1) return 1;\n  return n * factorial(n - 1);\n}",
    bigO: "Time O(n), Space O(n) recursion stack.",
    bigOWhy: "n recursive calls, mỗi call O(1) work. Stack depth n frames.",
    commonMistakes: "- Thiếu base case → stack overflow.\n- Base case sai (return 0 thay vì 1).\n- Không handle n=0.",
    compareApproaches: "Recursive elegant O(n) stack. Iterative O(1) space — preferred production. BigInt cho n lớn.",
    interviewTips: "- Luôn viết base case TRƯỚC.\n- Vẽ call stack khi giải thích.\n- Mention stack overflow khi n lớn.",
    notes: "JS number overflow ~170!. Dùng BigInt cho bài toán lớn.",
  },

  fibonacci_recursive: {
    title: "5.2 Fibonacci — Đệ quy thuần (Naive)",
    meaning: "fib(n) = fib(n-1) + fib(n-2); fib(0)=0, fib(1)=1. Dãy 0,1,1,2,3,5,8,13...",
    definition: "Trực tiếp dịch công thức thành code recursive — mỗi call tách thành 2 sub-calls.",
    whyLearn: "Fibonacci naive là ví dụ sống động nhất về overlapping subproblems — tại sao cần memoization/DP. So sánh O(2^n) vs O(n).",
    analogy: "Giống lan truyền tin đồn: để biết fib(5), hỏi fib(4) và fib(3); fib(4) lại hỏi fib(3) — fib(3) bị hỏi nhiều lần.",
    algorithmSteps: "1. Base: n<=1 return n.\n2. Return fib(n-1) + fib(n-2).\n3. Trace tree để thấy overlap.\n4. So sánh với memo version.\n5. Iterative: a,b swap loop.",
    howItWorks: "Recursion tree exponential nodes — fib(5) gọi fib(3) 2 lần, fib(2) 3 lần. Không nhớ kết quả → tính lại → O(2^n).",
    dryRun: "fib(5)\n\nfib(5)=fib(4)+fib(3)\n fib(4)=fib(3)+fib(2)\n  fib(3)=fib(2)+fib(1) ...\n\nfib(3) tính 2 lần!\nfib(2) tính 3 lần!",
    visualization: "Recursion tree fib(5):\n        5\n      /   \\\n     4     3\n    / \\   / \\\n   3  2  2  1\n  ... overlap tại 3,2",
    codePattern: "export function fibonacci(n) {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}",
    bigO: "Time O(2^n), Space O(n) stack depth.",
    bigOWhy: "Mỗi call 2 children → binary tree ~2^n nodes. Depth n → O(n) stack.",
    commonMistakes: "- Nghĩ recursive = always elegant — fib naive quá chậm.\n- Base case off-by-one.\n- Không nhận ra overlap → miss DP opportunity.",
    compareApproaches: "Naive O(2^n) vs memo O(n) vs DP O(n) vs matrix exp O(log n). Luôn mention upgrade path trong interview.",
    interviewTips: "- Sau naive, offer memoization — shows growth.\n- Draw recursion tree cho n=5.\n- Iterative 2-variable O(1) space.",
    notes: "Dùng bài này để transition sang fibonacci_memo và fibonacci_dp.",
  },

  reverse_string_recursive: {
    title: "5.3 Đảo chuỗi — Đệ quy",
    meaning: "Reverse string bằng cách swap hai đầu rồi đệ quy phần giữa.",
    definition: "reverse(s, l, r): if l>=r return; swap s[l],s[r]; reverse(s,l+1,r-1). Tương đương two-pointer nhưng dùng call stack.",
    whyLearn: "Luyện divide-and-conquer thinking và hiểu recursion thay thế loop. Pattern cho reverse array, palindrome check recursive.",
    analogy: "Giống gập chuỗi: đổi hai đầu, bỏ đi, tiếp tục với phần giữa ngắn hơn — cho đến khi còn 0-1 ký tự.",
    algorithmSteps: "1. Chuyển string thành char array.\n2. helper(arr, left, right).\n3. Base: left >= right return.\n4. Swap arr[left], arr[right].\n5. helper(arr, left+1, right-1).",
    howItWorks: "Mỗi recursive call xử lý 1 cặp swap. Stack depth n/2. Khi unwind không cần — kết quả đã mutate array.",
    dryRun: "reverse(\"hello\", 0, 4)\n\nswap h↔o → \"oellh\", call(1,3)\nswap e↔l → \"olleh\", call(2,2)\nleft>=right → return",
    visualization: "hello L=0 R=4 → oellh\n     L=1 R=3 → olleh\n     L=2 R=2 → done",
    codePattern: "export function reverseStringRecursive(s) {\n  const a = s.split('');\n  function rev(l, r) { if (l >= r) return; [a[l], a[r]] = [a[r], a[l]]; rev(l+1, r-1); }\n  rev(0, a.length-1);\n  return a.join('');\n}",
    bigO: "Time O(n), Space O(n) stack + array.",
    bigOWhy: "n/2 swaps, n/2 stack frames. Array O(n).",
    commonMistakes: "- Base case left>right vs left>=right.\n- Không mutate được string trực tiếp.\n- Stack overflow với string cực dài.",
    compareApproaches: "Iterative two-pointer O(1) stack — preferred. Recursive teaches divide-and-conquer. Functional: reverse(tail) + head.",
    interviewTips: "- Viết iterative trước, recursive khi asked.\n- Explain stack depth = n/2.\n- Tail recursion (JS không optimize).",
    notes: "Functional style: reverse(s.slice(1)) + s[0] — O(n²) do slice, không khuyến khích.",
  },

  bubble_sort: {
    title: "6.1 Bubble Sort",
    meaning: "Sắp xếp bằng cách so sánh cặp liền kề, swap nếu sai thứ tự — phần tử lớn 'nổi' lên cuối mỗi pass.",
    definition: "n-1 passes. Mỗi pass: j từ 0 đến end-i-1, swap nếu arr[j]>arr[j+1]. Early exit nếu không swap.",
    whyLearn: "Bubble sort dạy invariant (sorted suffix), stable sort, và O(n²) comparison sorts. Dễ trace dry-run — foundation trước merge/quick.",
    analogy: "Giống bọt khí trong nước — phần tử lớn nhất nổi lên trên (cuối mảng) sau mỗi vòng quét.",
    algorithmSteps: "1. For i = 0 to n-2 (số passes).\n2. swapped = false.\n3. For j = 0 to n-2-i: if arr[j]>arr[j+1], swap.\n4. If !swapped break (optimized).\n5. Sau pass i, phần tử lớn nhất ở vị trí n-1-i.",
    howItWorks: "Mỗi pass đảm bảo max của unsorted region đến đúng vị trí. Shrinking unsorted window. Stable vì chỉ swap khi strictly greater.",
    dryRun: "5 1 3 8 4 6 9 2\n\nPass1: 1 3 5 4 6 8 2 9 (9 nổi lên)\nPass2: 1 3 4 5 6 2 8 9\n...\nFinal: 1 2 3 4 5 6 8 9",
    visualization: "Pass 1 comparisons (| = compare/swap):\n5 1 3 8 4 6 9 2\n| |\n1 5 3 8 4 6 9 2\n  | |\n...\n→ 9 bubbles to end",
    codePattern: "export function bubbleSort(arr) {\n  const a = [...arr];\n  for (let i = 0; i < a.length - 1; i++) {\n    let swapped = false;\n    for (let j = 0; j < a.length - 1 - i; j++) {\n      if (a[j] > a[j+1]) { [a[j], a[j+1]] = [a[j+1], a[j]]; swapped = true; }\n    }\n    if (!swapped) break;\n  }\n  return a;\n}",
    bigO: "Time O(n²) worst/average, O(n) best (sorted+optimized). Space O(1). Stable.",
    bigOWhy: "Double loop n passes × n comparisons. Best case 1 pass nếu sorted. In-place swaps only.",
    commonMistakes: "- Inner loop bound sai (phải n-1-i).\n- Quên optimized early exit.\n- Nhầm stable — bubble IS stable.",
    compareApproaches: "Bubble O(n²) didactic only. Insertion better for small/nearly sorted. Merge/Quick O(n log n) production.",
    interviewTips: "- Trace 1 pass trên whiteboard.\n- Nêu stable + in-place.\n- Biết khi nào O(n) best case.",
    notes: "Không dùng production — chỉ học invariant và stable sort concept.",
  },

  selection_sort: {
    title: "6.2 Selection Sort",
    meaning: "Mỗi pass tìm min của phần unsorted, swap với phần tử đầu unsorted.",
    definition: "For i=0..n-2: tìm minIndex từ i đến n-1, swap arr[i] và arr[minIndex]. Sorted prefix tăng dần.",
    whyLearn: "Selection sort có đúng n swaps — hữu ích khi write cost cao. Hiểu trade-off: ít swap nhưng vẫn O(n²) comparisons.",
    analogy: "Giống chọn đội bóng: mỗi vòng chọn người giỏi nhất còn lại đưa vào vị trí tiếp theo.",
    algorithmSteps: "1. For i = 0 to n-2.\n2. minIdx = i.\n3. For j = i+1 to n-1: if arr[j]<arr[minIdx], minIdx=j.\n4. Swap arr[i], arr[minIdx].\n5. Repeat — sorted prefix [0..i].",
    howItWorks: "Invariant: arr[0..i-1] sorted. Mỗi step đặt đúng phần tử thứ i. Không stable — swap xa có thể đổi thứ tự equal elements.",
    dryRun: "[64,25,12,22,11]\ni=0: min=11 idx=4 → [11,25,12,22,64]\ni=1: min=12 → [11,12,25,22,64]\n...→ [11,12,22,25,64]",
    visualization: "i→ [11 | 25 12 22 64]  min=11 swap\n   [11 12 | 25 22 64]  min=12 swap\n   sorted↑  unsorted→",
    codePattern: "export function selectionSort(arr) {\n  const a = [...arr];\n  for (let i = 0; i < a.length - 1; i++) {\n    let min = i;\n    for (let j = i + 1; j < a.length; j++) if (a[j] < a[min]) min = j;\n    [a[i], a[min]] = [a[min], a[i]];\n  }\n  return a;\n}",
    bigO: "Time O(n²) always, Space O(1). Unstable. Exactly n-1 swaps.",
    bigOWhy: "Luôn quét remaining n-i elements — không adaptive. Swaps minimal.",
    commonMistakes: "- Tìm max thay vì min (descending OK nhưng phải consistent).\n- Swap trong inner loop thay vì sau khi tìm min.\n- Nghĩ selection sort stable — KHÔNG stable.",
    compareApproaches: "Selection: min swaps. Insertion: adaptive O(n) nearly sorted. Bubble: stable nhưng nhiều swap.",
    interviewTips: "- Nêu unstable với ví dụ equal elements.\n- Khi write-heavy: selection có advantage.\n- Trace minIndex trên example.",
    notes: "Unstable example: [2a, 2b, 1] → [1, 2b, 2a] — 2a và 2b đổi thứ tự.",
  },

  insertion_sort: {
    title: "6.3 Insertion Sort",
    meaning: "Xây sorted prefix: mỗi phần tử mới chèn vào đúng vị trí trong phần đã sort (shift phải).",
    definition: "For i=1..n-1: lưu key=arr[i], shift arr[j]>key sang phải, insert key vào hole.",
    whyLearn: "Insertion sort adaptive — O(n) khi nearly sorted. Là building block của TimSort. Dễ implement, stable, tốt cho small n.",
    analogy: "Giống sắp bài trên tay: mỗi lá mới chèn vào đúng chỗ trong các lá đã xếp — dịch các lá lớn hơn sang phải.",
    algorithmSteps: "1. For i = 1 to n-1.\n2. key = arr[i], j = i-1.\n3. While j>=0 và arr[j]>key: arr[j+1]=arr[j], j--.\n4. arr[j+1] = key.\n5. arr[0..i] now sorted.",
    howItWorks: "Sorted invariant mở rộng 1 phần tử mỗi iteration. Shift thay vì swap nhiều — stable. Best case sorted array: inner while không chạy → O(n).",
    dryRun: "[5,2,4,6,1,3]\ni=1 key=2: shift 5 → [5,5,4,6,1,3] insert → [2,5,4,6,1,3]\ni=2 key=4: [2,4,5,6,1,3]\n...\n→ [1,2,3,4,5,6]",
    visualization: "     sorted | unsorted\n[2 5 4 | 6 1 3]  key=4, shift 5, insert 4\n[2 4 5 | 6 1 3]",
    codePattern: "export function insertionSort(arr) {\n  const a = [...arr];\n  for (let i = 1; i < a.length; i++) {\n    const key = a[i]; let j = i - 1;\n    while (j >= 0 && a[j] > key) { a[j+1] = a[j]; j--; }\n    a[j+1] = key;\n  }\n  return a;\n}",
    bigO: "Time O(n²) worst, O(n) best (sorted), O(n+k) nearly sorted. Space O(1). Stable.",
    bigOWhy: "Worst: each i shifts O(i) → sum i = O(n²). Best: no shifts. Stable: equal elements not passed by key.",
    commonMistakes: "- Dùng swap thay shift → unstable và khác thuật toán.\n- j loop condition off-by-one.\n- Quên key variable, overwrite during shift.",
    compareApproaches: "Insertion best adaptive simple sort. Merge stable O(n log n). Quick faster average unstable.",
    interviewTips: "- Nêu O(n) nearly sorted — TimSort uses this.\n- Stable sort ví dụ.\n- Good for small n (<50) in practice.",
    notes: "Online algorithm — có thể sort stream từng phần tử một.",
  },

  merge_sort: {
    title: "6.4 Merge Sort",
    meaning: "Chia đôi mảng, sort recursive từng nửa, merge hai nửa sorted — divide and conquer.",
    definition: "base: length<=1 return. split mid, left=sort(left), right=sort(right), return merge(left,right). Merge dùng two-pointer.",
    whyLearn: "Merge sort là stable O(n log n) guaranteed — không worst case như quick sort. Nền tảng external sorting, inversion count, merge k lists.",
    analogy: "Giống chia bài: chia đôi chồng bài, sort từng nửa, rồi trộn hai chồng đã xếp thành một — trộn là merge step quen thuộc.",
    algorithmSteps: "1. If n<=1 return arr.\n2. mid = floor(n/2).\n3. left = mergeSort(arr[0..mid]).\n4. right = mergeSort(arr[mid..n]).\n5. return merge(left, right) — two-pointer.",
    howItWorks: "Recursion tree log n levels, mỗi level merge tổng O(n) work → O(n log n). Stable nếu merge dùng <= khi equal.",
    dryRun: "[38,27,43,3]\n\nsplit [38,27] [43,3]\n[38][27]→[27,38]  [43][3]→[3,43]\nmerge→[3,27,38,43]",
    visualization: "        [38,27,43,3]\n       /            \\\n  [38,27]          [43,3]\n   /    \\           /   \\\n[38]  [27]       [43]  [3]\n  \\    /           \\    /\n[27,38]           [3,43]\n       \\            /\n      [3,27,38,43]",
    codePattern: "export function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = arr.length >> 1;\n  return merge(mergeSort(arr.slice(0,mid)), mergeSort(arr.slice(mid)));\n}\nfunction merge(a,b){ /* two-pointer */ }",
    bigO: "Time O(n log n) always, Space O(n) auxiliary (merge temp array). Stable.",
    bigOWhy: "log n levels × O(n) merge per level. Temp arrays hold n elements total across level.",
    commonMistakes: "- Merge không stable (dùng < thay <=).\n- Quên base case → infinite recursion.\n- In-place merge on array khó — thường O(n) extra.",
    compareApproaches: "Merge: stable O(n log n), O(n) space. Quick: O(1) extra, unstable, faster cache. Heap: O(n log n) in-place unstable.",
    interviewTips: "- Viết merge() trước — reusable.\n- Draw recursion tree.\n- Follow-up: inversion count, merge k lists.",
    notes: "Bottom-up iterative merge sort có thể O(1) extra với careful indexing — advanced.",
  },

  quick_sort: {
    title: "6.5 Quick Sort",
    meaning: "Chọn pivot, partition nhỏ hơn trái lớn hơn phải, recursive sort hai bên.",
    definition: "pick pivot (last/first/random), partition in-place, pivot vào đúng vị trí, sort left và right subarrays.",
    whyLearn: "Quick sort fastest average comparison sort — standard library sort thường hybrid Quick+Insertion. Partition skill dùng cho quickselect, Dutch flag.",
    analogy: "Giống sắp người theo chiều cao: chọn 1 người làm mốc, người thấp hơn đứng trái, cao hơn đứng phải, rồi làm lại từng nhóm.",
    algorithmSteps: "1. if low>=high return.\n2. pivot = arr[high] (hoặc random).\n3. partition: i=low, j scan, swap nhỏ hơn pivot lên.\n4. swap pivot vào vị trí i (pivot index).\n5. quickSort(low, pi-1), quickSort(pi+1, high).",
    howItWorks: "Partition O(n) đặt pivot đúng chỗ. Average split đôi → log n depth → O(n log n). Worst pivot sorted → O(n²).",
    dryRun: "[10,80,30,90,40] pivot=40\n\npartition → [10,30,40,90,80] pivot idx=2\nsort left [10,30], right [90,80]",
    visualization: "pivot=40\n[10 80 30 90 40]\n ↑        ↑ scan swap smaller left\n→ [10 30 ... 40 | 90 80]",
    codePattern: "export function quickSort(arr, lo=0, hi=arr.length-1) {\n  if (lo >= hi) return arr;\n  const pi = partition(arr, lo, hi);\n  quickSort(arr, lo, pi-1); quickSort(arr, pi+1, hi);\n  return arr;\n}",
    bigO: "Average O(n log n), Worst O(n²), Space O(log n) stack. Unstable.",
    bigOWhy: "Average balanced partition. Worst all elements one side. In-place partition O(1) extra.",
    commonMistakes: "- Pivot always min/max → O(n²) on sorted.\n- Partition off-by-one infinite loop.\n- Quên random pivot cho worst case mitigation.",
    compareApproaches: "Quick vs Merge: quick in-place faster cache; merge stable guaranteed. Introselect / median-of-three pivot tricks.",
    interviewTips: "- Implement partition Lomuto hoặc Hoare.\n- Mention randomized pivot.\n- Quickselect O(n) average — kth element.",
    notes: "Sorted input + last pivot = worst case — always mention random pivot in interview.",
  },

  heap_sort: {
    title: "6.6 Heap Sort",
    meaning: "Build max heap, liên tục swap root (max) với phần tử cuối unsorted, heapify — in-place O(n log n).",
    definition: "heapify array thành max heap. For end=n-1 down to 1: swap arr[0],arr[end], heapify root với size=end.",
    whyLearn: "Heap sort guaranteed O(n log n) in-place — không extra array như merge. Hiểu heapify + heap sort = master heap data structure.",
    analogy: "Giống xếp hàng theo chiều cao dùng cây phân cấp: người cao nhất (root) ra khỏi hàng, còn lại sắp lại heap.",
    algorithmSteps: "1. buildMaxHeap: heapify từ last parent down to 0.\n2. For i=n-1 down to 1: swap arr[0],arr[i].\n3. heapify(arr, 0, i) — heap size giảm.\n4. Sau loop arr sorted ascending.\n5. heapify: compare with children, swap larger child up.",
    howItWorks: "Max heap property: parent >= children. Extract max to end shrinks heap. buildHeap O(n) bottom-up — not n inserts.",
    dryRun: "[4,10,3,5,1]\nbuild heap → [10,5,3,4,1]\nswap 10↔1 → [1,5,3,4,10] heapify → [5,4,3,1,10]\n...→ [1,3,4,5,10]",
    visualization: "Max heap extract:\n   10        5\n  /  \\  →   / \\\n 5   3     4   3\n→ 10 goes to end (sorted suffix)",
    codePattern: "export function heapSort(arr) {\n  buildMaxHeap(arr);\n  for (let i = arr.length-1; i > 0; i--) {\n    [arr[0], arr[i]] = [arr[i], arr[0]];\n    heapify(arr, 0, i);\n  }\n  return arr;\n}",
    bigO: "Time O(n log n) always, Space O(1). Unstable.",
    bigOWhy: "n extractions × O(log n) heapify. buildHeap O(n). No extra arrays.",
    commonMistakes: "- buildHeap top-down O(n log n) — dùng bottom-up O(n).\n- heapify wrong heap size boundary.\n- Dùng min heap cho ascending (cần max heap).",
    compareApproaches: "Heap sort vs Quick: heap guaranteed O(n log n), worse cache locality. vs Merge: heap O(1) space.",
    interviewTips: "- Know buildHeap O(n) proof sketch.\n- Link to priority queue / min heap problems.\n- Not cache-friendly — mention in system design.",
    notes: "Rare in practice vs Quick/Merge/TimSort — but great for space-constrained O(n log n).",
  },

  counting_sort: {
    title: "6.7 Counting Sort",
    meaning: "Đếm frequency mỗi giá trị integer trong range nhỏ, output theo thứ tự — không so sánh pairwise.",
    definition: "count[k] = số lần xuất hiện k. prefix sum cho vị trí stable. Duyệt input gán vào output hoặc rebuild in-place.",
    whyLearn: "Counting sort mở cánh cửa non-comparison sorts (radix, bucket). O(n+k) khi k nhỏ — faster than O(n log n) comparison bound.",
    analogy: "Giống đếm phiếu bầu: đếm mỗi ứng viên được bao nhiêu vote, rồi xếp theo số phiếu — không so sánh từng cặp.",
    algorithmSteps: "1. Tìm min, max hoặc range k.\n2. count array size k, init 0.\n3. For each x: count[x]++.\n4. Prefix sum count cho stable positions.\n5. Build output từ cuối input (stable) hoặc iterate count.",
    howItWorks: "Không comparison → beat O(n log n) lower bound. Trade-off: chỉ integer trong range k. Space O(k). Stable với backward pass.",
    dryRun: "arr=[4,2,2,8,3,3,1] range 1-8\ncount: 1→1, 2→2, 3→2, 4→1, 8→1\noutput: [1,2,2,3,3,4,8]",
    visualization: "Input:  4 2 2 8 3 3 1\nCount:  1:1 2:2 3:2 4:1 8:1\nOut:    1 2 2 3 3 4 8",
    codePattern: "export function countingSort(arr, maxVal) {\n  const count = new Array(maxVal+1).fill(0);\n  for (const x of arr) count[x]++;\n  const out = [];\n  for (let v=0; v<=maxVal; v++) for (let c=0; c<count[v]; c++) out.push(v);\n  return out;\n}",
    bigO: "Time O(n + k), Space O(n + k), k = value range. Stable.",
    bigOWhy: "Count n elements + iterate k buckets. Linear when k = O(n).",
    commonMistakes: "- k quá lớn → memory explode.\n- Negative numbers chưa shift index.\n- Unstable forward pass — dùng backward for stability.",
    compareApproaches: "Counting vs Radix: radix cho số nhiều digit. vs Comparison sorts: counting wins when k small.",
    interviewTips: "- Nêu điều kiện: integer, bounded range.\n- Stable version cho interview bonus.\n- Radix sort built on counting per digit.",
    notes: "k > n thì counting sort không hiệu quả — dùng comparison sort.",
  },

  radix_sort: {
    title: "6.8 Radix Sort",
    meaning: "Sort từng digit (hoặc byte) từ LSD hoặc MSD, dùng stable counting sort làm subroutine.",
    definition: "LSD: for digit d=0 to maxDigits: stable counting sort theo digit d. MSD: recursive partition by digit.",
    whyLearn: "Radix sort sort integers/strings fixed width in O(d*(n+k)) — used in practice for fixed-length keys, IP addresses, phone numbers.",
    analogy: "Giống sắp thư theo mã bưu điện: sort theo số cuối trước, rồi số kế cuối... cuối cùng cả dãy đúng — nhờ stable sort mỗi pass.",
    algorithmSteps: "1. Tìm max để biết số digits d.\n2. exp = 1 (ones), 10, 100...\n3. For each digit position: counting sort by (num/exp)%10.\n4. exp *= 10.\n5. LSD requires stable counting each pass.",
    howItWorks: "Stable digit sorts preserve relative order from previous passes. d passes × O(n+10) ≈ O(d*n). Works for non-negative integers typically.",
    dryRun: "arr=[170,45,75,90,802,24,2,66]\n\npass1 (ones): 170,90,802,2,24,45,75,66\npass2 (tens): 802,2,24,45,66,170,75,90\npass3 (hundreds): 2,24,45,66,75,90,170,802",
    visualization: "LSD passes:\nOnes  → bucket by last digit\nTens  → bucket by 2nd digit (stable)\n100s  → final sorted",
    codePattern: "export function radixSort(arr) {\n  const max = Math.max(...arr);\n  for (let exp = 1; Math.floor(max/exp) > 0; exp *= 10)\n    countingSortByDigit(arr, exp);\n  return arr;\n}",
    bigO: "Time O(d * (n + k)), d=digits, k=base (10). Space O(n + k). Stable (LSD).",
    bigOWhy: "d passes of counting sort O(n+k) each. d = log10(max) for integers.",
    commonMistakes: "- Unstable subroutine → radix fails.\n- Negative numbers need offset/sign handling.\n- Không stable counting sort per digit.",
    compareApproaches: "LSD vs MSD: LSD simpler iterative. vs Merge O(n log n): radix wins large n, fixed small d.",
    interviewTips: "- Explain why STABLE counting required each pass.\n- LSD example with 3-digit numbers.\n- Mention real use: IP sorting.",
    notes: "Classic example arr with 170,45,75... — memorize dry-run for interview.",
  },

  linear_search: {
    title: "7.1 Linear Search",
    meaning: "Duyệt tuần tự từ đầu đến cuối tìm target — simplest search.",
    definition: "For i=0..n-1: if arr[i]==target return i. Return -1 nếu không thấy. Không cần sorted.",
    whyLearn: "Linear search là baseline — mọi complex search đều so sánh với này. Hiểu khi O(n) acceptable và khi cần upgrade binary search.",
    analogy: "Giống tìm đồ trong túi: lục từng ngăn một cho đến khi thấy — không cần túi được sắp xếp.",
    algorithmSteps: "1. For i from 0 to n-1.\n2. If arr[i] === target return i.\n3. Optional: early break khi found.\n4. Return -1 if end.\n5. Works on any array/linked list.",
    howItWorks: "Worst case check all n elements. Best case O(1) if target at index 0. No preprocessing — works unsorted, linked list.",
    dryRun: "arr=[4,2,7,1,9], target=7\n\ni=0: 4≠7\ni=1: 2≠7\ni=2: 7==7 → return 2",
    visualization: "[4][2][7][1][9]\n  ↑  ↑  ✓\n  i=0,1,2 found",
    codePattern: "export function linearSearch(arr, target) {\n  for (let i = 0; i < arr.length; i++) if (arr[i] === target) return i;\n  return -1;\n}",
    bigO: "Time O(n), Space O(1).",
    bigOWhy: "n comparisons worst case. No extra structure.",
    commonMistakes: "- Dùng binary search on unsorted — wrong.\n- Return 0 thay -1 khi not found.\n- Off-by-one loop bound.",
    compareApproaches: "Linear O(n) vs Binary O(log n) on sorted. Hash lookup O(1) average with preprocessing O(n).",
    interviewTips: "- Nêu precondition: không cần sorted.\n- Sentinel search variant — minor optimization.\n- When n small, linear fine.",
    notes: "Linked list chỉ có linear search — không random access cho binary.",
  },

  binary_search: {
    title: "7.2 Binary Search",
    meaning: "Chia đôi không gian tìm kiếm trên mảng sorted — loại một nửa mỗi bước.",
    definition: "left=0, right=n-1. mid=(left+right)>>1. if arr[mid]==target return; elif arr[mid]<target left=mid+1; else right=mid-1.",
    whyLearn: "Binary search là algorithm quan trọng nhất cho sorted data — và template generalized cho rotated array, first/last occurrence, search on answer.",
    analogy: "Tra từ điển: mở giữa, từ cần tìm so với trang giữa — bỏ nửa trái hoặc phải, lặp lại.",
    algorithmSteps: "1. left=0, right=n-1.\n2. While left<=right.\n3. mid = left + ((right-left)>>1) — tránh overflow.\n4. Compare arr[mid] với target.\n5. Thu hẹp left hoặc right. Return -1 nếu loop end.",
    howItWorks: "Mỗi iteration loại nửa còn lại → log n steps. Requires total order và random access. Template left<=right vs left<right tùy bài.",
    dryRun: "sorted [1,3,5,7,9,11], target=7\n\nL=0,R=5 mid=2 arr[2]=5<7 → L=3\nL=3,R=5 mid=4 arr[4]=9>7 → R=3\nL=3,R=3 mid=3 arr[3]=7 ✓",
    visualization: "[1 3 5 7 9 11]  target=7\n       L   M   R\n       → narrow → found M",
    codePattern: "export function binarySearch(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = lo + ((hi - lo) >> 1);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1; else hi = mid - 1;\n  }\n  return -1;\n}",
    bigO: "Time O(log n), Space O(1) iterative; O(log n) recursive stack.",
    bigOWhy: "Halve search space each step → log2(n) iterations.",
    commonMistakes: "- mid overflow (use lo+(hi-lo)/2).\n- Infinite loop: wrong lo=mid vs lo=mid+1.\n- Apply on unsorted array.",
    compareApproaches: "Standard vs lower_bound (first >= target) vs upper_bound. Binary search on answer for optimization problems.",
    interviewTips: "- Memorize template left<=right.\n- Clarify duplicates: first vs any occurrence.\n- log 100 ≈ 7 — only ~7 steps for 100 elements.",
    notes: "log₂(10⁹) ≈ 30 — binary search scales incredibly well.",
  },

  tree_traversals: {
    title: "7.3 Tree Traversals (DFS)",
    meaning: "Ba cách duyệt binary tree: inorder (LNR), preorder (NLR), postorder (LRN).",
    definition: "Inorder: left, node, right → BST sorted. Preorder: node first → serialize/copy. Postorder: children before node → delete tree.",
    whyLearn: "Tree traversals xuất hiện trong BST, expression trees, serialize/deserialize, path problems. Phải code được cả recursive và iterative.",
    analogy: "Preorder: chụp ảnh node trước khi vào nhánh. Inorder: đọc BST như sách từ nhỏ đến lớn. Postorder: dọn nhánh con trước khi dọn cha.",
    algorithmSteps: "1. Inorder: dfs(left), visit(node), dfs(right).\n2. Preorder: visit, dfs(left), dfs(right).\n3. Postorder: dfs(left), dfs(right), visit.\n4. Iterative inorder: stack push left chain, pop, visit, go right.\n5. BFS level-order dùng queue — khác 3 DFS này.",
    howItWorks: "Recursive = DFS với visit timing khác nhau. Stack simulation cho iterative. Inorder iterative classic interview question.",
    dryRun: "Tree: 9,4,20,1,5,9,170\n\nInorder: 1,4,5,9,9,20,170\nPreorder: 9,4,1,5,20,9,170\nPostorder: 1,5,4,9,170,20,9",
    visualization: "        9\n       / \\\n      4   20\n     /\\   /\\\n    1 5  9 170\n\nInorder: left-root-right along tree",
    codePattern: "export function treeTraversals(root) {\n  const ino=[], pre=[], post=[];\n  function dfs(n){ if(!n)return; pre.push(n.value); dfs(n.left); ino.push(n.value); dfs(n.right); post.push(n.value); }\n  dfs(root); return { inorder: ino, preorder: pre, postorder: post };\n}",
    bigO: "Time O(n) all nodes once, Space O(h) stack h=height.",
    bigOWhy: "Visit each node exactly once. Stack depth = tree height.",
    commonMistakes: "- Nhầm inorder vs preorder output.\n- Quên null check base case.\n- Iterative inorder: push right once wrong.",
    compareApproaches: "Recursive clean. Iterative avoids stack overflow deep tree. Morris traversal O(1) space — advanced.",
    interviewTips: "- Code inorder iterative with stack.\n- BST inorder = sorted — mention always.\n- Serialize tree = preorder with null markers.",
    notes: "Nhớ code 2 dạng: iterative và recursive cho mỗi traversal — theo explain_dsa.md style.",
  },

  validate_bst: {
    title: "7.4 Validate Binary Search Tree",
    meaning: "Kiểm tra cây có thỏa BST property: mọi node trái < node < mọi node phải (toàn cây).",
    definition: "Không đủ so sánh parent-child trực tiếp. Cần range (min, max) hợp lệ cho mỗi node hoặc inorder strictly increasing.",
    whyLearn: "Classic trap question — naive compare parent-child fails. Tests understanding BST global property vs local.",
    analogy: "Giống kiểm tra xếp hàng theo chiều cao: không chỉ người đứng trước/sau bạn đúng, mà TẤT CẢ bên trái thấp hơn, TẤT CẢ bên phải cao hơn.",
    algorithmSteps: "1. DFS(node, min, max): null → true.\n2. If node.val <= min or >= max → false.\n3. Return dfs(left, min, node.val) && dfs(right, node.val, max).\n4. Inorder: track prev, must be strictly increasing.\n5. Init range (-∞, +∞).",
    howItWorks: "Range propagation: left child max bound = parent value, right child min bound = parent value. Inorder alternative: any drop in sequence invalidates.",
    dryRun: "    5\n   / \\\n  1   6\n     / \\\n    4   7\n\nNode 4 < parent 6 OK locally but 4 < root 5 in right subtree → INVALID",
    visualization: "Trap tree:\n    5\n   / \\\n  1   4   ← 4 in right of 5 but 4<5\nINVALID",
    codePattern: "export function validateBst(root) {\n  function ok(n, lo, hi) {\n    if (!n) return true;\n    if (n.value <= lo || n.value >= hi) return false;\n    return ok(n.left, lo, n.value) && ok(n.right, n.value, hi);\n  }\n  return ok(root, -Infinity, Infinity);\n}",
    bigO: "Time O(n), Space O(h) recursion.",
    bigOWhy: "Visit every node once. Stack height h.",
    commonMistakes: "- Chỉ check node.left < node < node.right — FAILS trap case.\n- Duplicate values: BST thường require strict < >.\n- Int boundary: dùng null hoặc -Infinity/Infinity.",
    compareApproaches: "Range DFS vs inorder prev pointer. Both O(n). Inorder elegant for threaded trees.",
    interviewTips: "- Draw trap case 5,1,6,4,7 first.\n- Clarify duplicate policy with interviewer.\n- Mention Integer.MIN_VALUE edge with inorder.",
    notes: "Đây là bài phân biệt hiểu BST thật vs hiểu surface.",
  },

  dijkstra_shortest_path: {
    title: "8.1 Dijkstra — Shortest Path (non-negative weights)",
    meaning: "Tìm đường đi ngắn nhất từ source tới mọi node với trọng số cạnh ≥ 0.",
    definition: "Greedy + relaxation: luôn xử lý node chưa settled có dist nhỏ nhất (min-heap). Cập nhật dist[neighbor] = min(dist[neighbor], dist[u]+w).",
    whyLearn: "Dijkstra là thuật toán graph quan trọng nhất thực tế — GPS routing, network routing, game pathfinding với cost. Mọi senior dev cần implement được.",
    analogy: "Giống lan truyền tin đồn có chi phí: từ điểm xuất phát, tin đến node rẻ nhất trước, cập nhật chi phí đến hàng xóm nếu đi qua node này rẻ hơn.",
    algorithmSteps: "1. dist[start]=0, còn lại ∞. Min-heap (dist, node).\n2. Pop node u nhỏ nhất dist.\n3. Nếu u đã settled skip (lazy).\n4. For neighbor v: if dist[u]+w < dist[v], update + push heap.\n5. Repeat đến heap rỗng.",
    howItWorks: "Greedy đúng vì weights non-negative — khi settle u, dist[u] là optimal. Heap giảm extract-min từ O(V) xuống O(log V).",
    dryRun: "A→B:1, A→C:4, B→C:2, B→D:5, C→D:1\n\nstart A: dist A=0\npop A: B=1, C=4\npop B: C=min(4,3)=3, D=6\npop C: D=min(6,4)=4",
    visualization: "Graph with weights:\n  A --1-- B\n  |       |\n  4       5\n  |       |\n  C --1-- D\n\nShortest A→D: A-B-C-D = 4",
    codePattern: "export function dijkstra(graph, start) {\n  const dist = new Map([[start, 0]]);\n  const pq = [[0, start]];\n  while (pq.length) {\n    pq.sort((a,b)=>a[0]-b[0]);\n    const [d,u] = pq.shift();\n    if (d > (dist.get(u) ?? Infinity)) continue;\n    for (const [v,w] of graph.get(u) ?? []) {\n      const nd = d + w;\n      if (nd < (dist.get(v) ?? Infinity)) { dist.set(v, nd); pq.push([nd, v]); }\n    }\n  }\n  return dist;\n}",
    bigO: "Time O((V+E) log V) với binary heap. Space O(V).",
    bigOWhy: "Mỗi edge relax có thể push heap → O(E log V). V pops O(V log V).",
    commonMistakes: "- Dùng Dijkstra với negative edge — SAI, dùng Bellman-Ford.\n- Không skip stale heap entries.\n- dist init sai (undefined vs Infinity).",
    compareApproaches: "Dijkstra non-negative vs BFS unweighted vs Bellman-Ford negative. A* = Dijkstra + heuristic.",
    interviewTips: "- State precondition: non-negative weights.\n- Mention lazy deletion in heap.\n- Grid Dijkstra = BFS when all weights 1.",
    notes: "Production: dùng proper MinHeap thay array sort mỗi pop.",
  },

  bellman_ford: {
    title: "8.2 Bellman-Ford — Shortest Path (negative weights OK)",
    meaning: "Relax tất cả edges V-1 lần — tìm shortest path kể cả negative weights, detect negative cycle.",
    definition: "dist[start]=0. Repeat V-1 times: for each edge (u,v,w): dist[v]=min(dist[v], dist[u]+w). V-th pass nếu còn relax được → negative cycle.",
    whyLearn: "Bellman-Ford xử lý negative edges mà Dijkstra không làm được — currency arbitrage, difference constraints, network routing protocols (RIP).",
    analogy: "Giống lan truyền tin chậm nhưng chắc: mỗi vòng mọi người hỏi hàng xóm 'có đường rẻ hơn không?' — sau V-1 vòng tin đã ổn định.",
    algorithmSteps: "1. dist[start]=0, others ∞.\n2. Loop V-1 times: relax all edges.\n3. relax(u,v,w): if dist[u]+w < dist[v], update.\n4. V-th iteration: any relax success → negative cycle.\n5. Return dist map hoặc flag cycle.",
    howItWorks: "Shortest path simple (no cycle) có tối đa V-1 edges → V-1 passes đủ. Negative cycle → dist giảm mãi. Slower than Dijkstra nhưng more general.",
    dryRun: "4 nodes, edges: 0→1:1, 1→2:-2, 2→3:3, 0→3:5\n\npass1: d[1]=1, d[2]=-1, d[3]=2\npass2: stable\nshortest 0→3 = 2",
    visualization: "Negative edge:\n0 --1→ 1\n      |\n     -2\n      ↓\n      2 --3→ 3\n\n1→2 weight -2 allows shortcut",
    codePattern: "export function bellmanFord(n, edges, start) {\n  const dist = Array(n).fill(Infinity); dist[start]=0;\n  for (let i=0;i<n-1;i++) for (const [u,v,w] of edges) if (dist[u]+w < dist[v]) dist[v]=dist[u]+w;\n  for (const [u,v,w] of edges) if (dist[u]+w < dist[v]) return { hasNegativeCycle: true };\n  return { dist };\n}",
    bigO: "Time O(V*E), Space O(V).",
    bigOWhy: "V-1 passes × E edges each. No heap overhead.",
    commonMistakes: "- Chỉ relax từ start reachable — OK nhưng dist ∞ nodes stay ∞.\n- Quên V-th pass cycle detection.\n- Dùng Bellman-Ford khi Dijkstra đủ — overkill.",
    compareApproaches: "BF O(VE) general vs Dijkstra O(E log V) non-neg. SPFA average faster but worst O(VE). Floyd-Warshall all-pairs O(V³).",
    interviewTips: "- Explain V-1 passes intuition (max path length).\n- Negative cycle detection = 1 extra pass.\n- Currency arbitrage application.",
    notes: "Edge list format natural for Bellman-Ford — không cần adjacency list.",
  },

  fibonacci_memo: {
    title: "9.1 Fibonacci — Top-Down Memoization",
    meaning: "Đệ quy + cache kết quả subproblem đã tính — tránh overlapping recomputation.",
    definition: "memo = {}. fib(n): if n in memo return; if n<=1 return n; memo[n]=fib(n-1)+fib(n-2); return memo[n].",
    whyLearn: "Memoization là bridge từ naive recursion sang DP. Top-down intuitive — chỉ tính subproblems cần thiết. Pattern cho DFS + cache (word break, coin change).",
    analogy: "Giống làm bài tập có đáp án sẵn ở sách: fib(3) tính 1 lần, ghi vào memo, lần sau hỏi fib(3) mở sách ra — không tính lại.",
    algorithmSteps: "1. Tạo memo Map hoặc array.\n2. Base case n<=1 return n.\n3. If memo[n] exists return memo[n].\n4. Compute fib(n-1)+fib(n-2).\n5. Store và return memo[n].",
    howItWorks: "Recursion tree pruned — mỗi n tính 1 lần. O(n) subproblems, O(n) work total. Stack depth still O(n) — có thể stack overflow n lớn.",
    dryRun: "fib(5) with memo:\n\nfib(5) needs fib(4), fib(3)\nfib(4) needs fib(3) — fib(3) FROM MEMO!\nOnly computes: 5,4,3,2,1,0 → 6 calls vs 15 naive",
    visualization: "Naive tree pruned:\n      5\n    /   \\\n   4     3(cached)\n  / \\\n 3   2\n(cached after first visit)",
    codePattern: "export function fibonacciMemo(n, memo = {}) {\n  if (n <= 1) return n;\n  if (memo[n] != null) return memo[n];\n  memo[n] = fibonacciMemo(n-1, memo) + fibonacciMemo(n-2, memo);\n  return memo[n];\n}",
    bigO: "Time O(n), Space O(n) memo + O(n) stack.",
    bigOWhy: "n distinct subproblems, O(1) work each. Memo stores n entries.",
    commonMistakes: "- Quên return memo[n] sau khi compute.\n- Dùng object key số — OK trong JS.\n- Không pass memo qua recursive calls (new memo mỗi call).",
    compareApproaches: "Top-down memo vs bottom-up DP: same complexity, DP O(1) stack. Naive O(2^n) — always compare.",
    interviewTips: "- Start naive, identify overlap, add memo — show thought process.\n- Mention memo vs tabulation trade-offs.\n- Generalize: memo[state] pattern.",
    notes: "Template: if (memo.has(state)) return memo.get(state) — works for any DP.",
  },

  fibonacci_dp: {
    title: "9.2 Fibonacci — Bottom-Up DP (Tabulation)",
    meaning: "Lấp bảng dp từ base case lên — không cần recursion stack.",
    definition: "dp[0]=0, dp[1]=1. for i=2..n: dp[i]=dp[i-1]+dp[i-2]. Return dp[n]. Space optimize: chỉ 2 biến prev, curr.",
    whyLearn: "Bottom-up DP là default production approach — predictable O(1) stack, cache-friendly sequential access. Foundation cho knapsack, LCS, edit distance.",
    analogy: "Giống leo cầu thang: biết bậc 0 và bậc 1, tính bậc 2 từ 0+1, bậc 3 từ 1+2 — không cần hỏi lại bậc đã đếm.",
    algorithmSteps: "1. If n<=1 return n.\n2. dp[0]=0, dp[1]=1.\n3. For i=2 to n: dp[i]=dp[i-1]+dp[i-2].\n4. Return dp[n].\n5. Optimize: a=0,b=1, loop swap — O(1) space.",
    howItWorks: "Optimal substructure: fib(i) chỉ phụ thuộc fib(i-1), fib(i-2). Tính theo thứ tự tăng dần đảm bảo dependencies sẵn sàng.",
    dryRun: "n=6:\n\ndp[0]=0, dp[1]=1\ndp[2]=1, dp[3]=2, dp[4]=3, dp[5]=5, dp[6]=8",
    visualization: "dp table:\ni: 0  1  2  3  4  5  6\ndp: 0  1  1  2  3  5  8\n     ↑  ↑ fill left to right",
    codePattern: "export function fibonacciDp(n) {\n  if (n <= 1) return n;\n  let a = 0, b = 1;\n  for (let i = 2; i <= n; i++) { const c = a + b; a = b; b = c; }\n  return b;\n}",
    bigO: "Time O(n), Space O(1) optimized; O(n) with full dp array.",
    bigOWhy: "Single loop n iterations. Two variables suffice — only need last 2 values.",
    commonMistakes: "- Off-by-one loop (i<=n vs i<n).\n- Init dp wrong for n=0, n=1 edge.\n- Allocate full dp khi chỉ cần 2 vars.",
    compareApproaches: "DP O(1) space vs memo O(n) stack. Matrix exponentiation O(log n) — overkill unless n huge.",
    interviewTips: "- Write O(n) array first, optimize to O(1) space.\n- Define dp[i] meaning clearly aloud.\n- Connect to fibonacci_memo — same problem two techniques.",
    notes: "Luôn nêu dp[i] = số Fibonacci thứ i — definition drives transition.",
  },
};

export const SHARED_GUIDES = {
  dfsVsBfs: {
    title: "DFS vs BFS — So sánh chi tiết",
    meaning: "DFS = Tìm kiếm theo chiều sâu | BFS = Tìm kiếm theo chiều rộng",
    definition: "DFS đi sâu xuống nhánh trước khi backtrack. BFS duyệt hết các node cùng tầng (level) trước khi xuống tầng sâu hơn.",
    whyLearn: "DFS và BFS là hai pillar của graph/tree algorithms. Chọn sai = wrong complexity hoặc wrong answer (shortest path). Interview hỏi so sánh liên tục.",
    analogy: "BFS giống sóng nước lan từ tâm khi ném sỏi xuống hồ — loang đều theo vòng. DFS giống đi mê cung — chọn một hướng đi tới cuối, quay lại thử hướng khác.",
    algorithmSteps: "1. BFS: Queue FIFO, mark visited khi enqueue.\n2. DFS: Stack LIFO hoặc recursion, mark visited khi push/recurse.\n3. BFS: shortest path unweighted.\n4. DFS: cycle detect, topological sort, path enumeration.\n5. Cả hai: O(V+E) với adjacency list.",
    howItWorks: "BFS dùng Queue → node theo distance tăng dần. DFS dùng Stack → đi sâu trước. Memory: BFS O(width), DFS O(depth) — wide graph favor DFS memory.",
    dryRun: "Tree:\n        9\n    4       20\n  1   5   9  170\n\nBFS: [9,4,20,1,5,9,170]\nqueue: [9]→[4,20]→[1,5,9,170]\n\nDFS preorder: 9→4→1→5→20→9→170",
    visualization: "BFS levels:        DFS path:\n    9 (L0)              9\n  4   20 (L1)          /\n1 5 9 170 (L2)        4\n                     / \\\n                    1   5 ... deep first",
    codePattern: "// BFS\nconst q=[start], vis=new Set([start]);\nwhile(q.length){ const u=q.shift(); for(v of g[u]) if(!vis.has(v)){vis.add(v);q.push(v);} }\n// DFS\nfunction dfs(u){ vis.add(u); for(v of g[u]) if(!vis.has(v)) dfs(v); }",
    bigO: "Cả hai: Time O(V+E), Space O(V).",
    bigOWhy: "Mỗi vertex và edge xử lý tối đa 1 lần. Queue/Stack chứa tối đa O(V) nodes.",
    commonMistakes: "- Dùng DFS tìm shortest path unweighted — SAI.\n- BFS không mark visited khi enqueue → duplicate.\n- Nhầm DFS recursion với BFS level-order.",
    compareApproaches: "BFS shortest unweighted, multi-source BFS. DFS cycle, SCC, backtracking. Bidirectional BFS cho search space lớn.",
    interviewTips: "- Bảng so sánh: Stack vs Queue, depth vs breadth, shortest vs explore.\n- Grid problems: cả hai đều phổ biến.\n- Nêu memory trade-off wide vs deep graph.",
    notes: "Cần đường ngắn nhất (unweighted) → BFS. Cần explore paths / cycle → DFS.",
  },

  stableVsUnstable: {
    title: "Stable vs Unstable Sort",
    meaning: "Stable sort giữ thứ tự tương đối của các phần tử có cùng key/giá trị.",
    definition: "Sau sort, nếu arr[i] và arr[j] có cùng value và i<j ban đầu thì vị trí tương đối được giữ (stable). Unstable có thể hoán đổi thứ tự equal elements.",
    whyLearn: "Stability quan trọng khi sort multi-key (sort theo tên rồi theo điểm), database ORDER BY, UI lists. Chọn unstable sort khi không cần = faster options.",
    analogy: "Xếp hàng theo chiều cao: stable — hai người cùng 1m70 giữ thứ tự ai vào hàng trước. Unstable — có thể đổi chỗ họ sau khi sort.",
    algorithmSteps: "1. Xác định sort key (value hoặc field).\n2. Stable: Insertion, Merge, Bubble, Counting, Radix (LSD).\n3. Unstable: Quick, Heap, Selection.\n4. Test stability: sort [(1,'a'),(1,'b')] by key 1.\n5. Multi-key: sort stable theo key phụ trước, key chính sau.",
    howItWorks: "Stable = equal elements không 'nhảy' qua nhau. Merge stable khi merge dùng <=. Quick swap xa → unstable. Stability cần cho chained sorts.",
    dryRun: "Sort by value, keep letter order:\n[(2,a), (1,b), (1,a), (2,b)]\n\nStable result:\n[(1,b), (1,a), (2,a), (2,b)] — 1b before 1a? depends input order\nInput (1,b) before (1,a) → stable keeps that\n\nQuick sort may swap → (1,a) before (1,b)",
    visualization: "Equal keys (same height):\nBefore: A1 A2 (A1 arrived first)\nStable:  A1 A2\nUnstable: A2 A1 possible",
    codePattern: "// Stable merge: use <= when equal\nif (left[i] <= right[j]) take left[i++];\n// Unstable quick: partition swaps far apart",
    bigO: "Stability không đổi Big O — chỉ ảnh hưởng behavior với duplicates.",
    bigOWhy: "Stability là property behavior, không phải complexity class. Merge vẫn O(n log n) dù stable.",
    commonMistakes: "- Nghĩ Quick sort stable — KHÔNG.\n- Nghĩ Selection stable — KHÔNG.\n- Sort twice unstable không guarantee multi-key order.",
    compareApproaches: "Cần stability → Merge sort hoặc Insertion. Không cần → Quick faster average. TimSort = stable hybrid production.",
    interviewTips: "- Liệt kê stable/unstable từ memory.\n- Ví dụ multi-key sort students: name then score.\n- Java Arrays.sort objects stable; primitive not guaranteed.",
    notes: "Interview classic: liệt kê stable sorts — Insertion, Merge, Bubble, Counting, Radix.",
  },

  recursionAnatomy: {
    title: "Anatomy of Recursion — Giải phẫu Đệ quy",
    meaning: "Đệ quy = hàm gọi chính nó với input nhỏ hơn, hướng về base case.",
    definition: "Hai phần bắt buộc: Base case (điều kiện dừng, return trực tiếp) và Recursive case (gọi lại với problem nhỏ hơn). Call stack lưu mỗi frame.",
    whyLearn: "Recursion underpinning tree/graph DFS, divide-and-conquer, backtracking, DP top-down. Không hiểu call stack = debug recursion rất khó.",
    analogy: "Giống đứng giữa hai gương đối diện — ảnh lồng ảnh vô hạn, NHƯNG gương phải có điểm dừng (base case) nếu không nhìn mãi mãi.",
    algorithmSteps: "1. Define base case(s) — smallest input, return value.\n2. Define recursive case — gọi self với input tiến về base.\n3. Trust recursive call returns đúng (leap of faith).\n4. Combine sub-result với current step.\n5. Ensure progress toward base (không infinite).",
    howItWorks: "Mỗi call push stack frame (local vars, return address). Khi base hit, unwind — return values propagate lên. Depth d → O(d) stack space. Quá sâu → Stack Overflow.",
    dryRun: "factorial(4):\n\nfactorial(4)\n  4 * factorial(3)\n    3 * factorial(2)\n      2 * factorial(1)\n        1  ← base\n      = 2\n    = 6\n  = 24",
    visualization: "Call stack frames:\n[f(4): waiting ×f(3)]\n  [f(3): waiting ×f(2)]\n    [f(2): waiting ×f(1)]\n      [f(1): return 1]\n    ← unwind 2,6,24",
    codePattern: "export function factorial(n) {\n  if (n <= 1) return 1;        // BASE CASE first\n  return n * factorial(n-1); // RECURSIVE CASE\n}",
    bigO: "Time tùy problem. Space O(depth) stack frames — thường O(n) hoặc O(h) tree height.",
    bigOWhy: "Mỗi recursive call giữ frame trên stack cho đến unwind. Depth = số frame đồng thời tối đa.",
    commonMistakes: "- Thiếu base case → Stack Overflow.\n- Recursive case không tiến về base → infinite.\n- Không trust subcall — over-complicate.",
    compareApproaches: "Recursion vs Iteration: same logic, recursion = implicit stack. Tail recursion (JS không optimize TCO). Convert recursion → explicit stack.",
    interviewTips: "- LUÔN viết base case trước khi code recursive case.\n- Vẽ call tree cho fib(5) hoặc factorial(4).\n- Mention stack overflow risk và khi dùng iterative.",
    notes: "Template: if (base) return; else return combine(self(smaller)). Works for tree DFS, merge sort, backtracking.",
  },

  dpCore: {
    title: "Dynamic Programming — Core Ideas",
    meaning: "DP = tối ưu bằng cách nhớ kết quả subproblem, tránh tính lại overlapping work.",
    definition: "Hai điều kiện: (1) Optimal substructure — optimal solution chứa optimal sub-solutions. (2) Overlapping subproblems — cùng subproblem xuất hiện nhiều lần.",
    whyLearn: "DP giải hàng trăm bài interview: knapsack, LCS, edit distance, coin change, grid paths. Nhận ra DP pattern nhanh = competitive advantage lớn.",
    analogy: "Giống leo cầu thang: đếm cách lên bậc 10 = cách lên bậc 9 + cách lên bậc 8. Ghi nhớ bậc 9 một lần, dùng lại — không đếm lại từ đầu.",
    algorithmSteps: "1. Xác định state (vd: dp[i], dp[i][j]).\n2. Viết recurrence relation.\n3. Base cases.\n4. Top-down: memo + recursion.\n5. Bottom-up: fill table theo thứ tự dependencies. Optimize space nếu chỉ cần few rows.",
    howItWorks: "Brute recursion → recursion tree exponential. Memo/DP table → mỗi state tính 1 lần → polynomial. Bottom-up tránh stack; top-down chỉ tính states cần.",
    dryRun: "fib(5) naive vs DP:\n\nNaive: fib(3) computed 2 times, fib(2) 3 times → 15 calls\n\nMemo: fib(0)..fib(5) each once → 6 calls\ndp: [0,1,1,2,3,5] fill left to right",
    visualization: "Overlapping subproblems:\n        fib(5)\n       /    \\\n   fib(4)  fib(3) ← shared\n   /   \\    /   \\\nfib(3) fib(2) ...\n  ↑ overlap",
    codePattern: "// Top-down\nfunction fib(n, memo={}) { if(n<=1)return n; if(memo[n])return memo[n]; return memo[n]=fib(n-1,memo)+fib(n-2,memo); }\n// Bottom-up\nlet a=0,b=1; for(let i=2;i<=n;i++){let c=a+b;a=b;b=c;} return b;",
    bigO: "Thường giảm từ O(2^n) hoặc O(n!) xuống O(n), O(n²), O(n*m) tùy states.",
    bigOWhy: "Số states × work per state. fib: n states O(1) each → O(n). Grid DP n×m table → O(nm).",
    commonMistakes: "- Nhầm greedy với DP — greedy không revisit subproblems.\n- Sai thứ tự fill bottom-up → dùng chưa tính state.\n- Không define dp[i] meaning rõ ràng.",
    compareApproaches: "Top-down memo: intuitive, sparse states OK. Bottom-up: no stack, often space optimize. fibonacci_recursive O(2^n) vs fibonacci_memo/dp O(n).",
    interviewTips: "- Check: optimal substructure + overlapping? → DP.\n- Define state và transition trước khi code.\n- Start O(n²) table, optimize space sau — shows mastery.",
    notes: "So sánh fibonacci_recursive (chậm) vs fibonacci_memo/dp (nhanh) — roadmap học DP trong curriculum này.",
  },
};
